package com.pippohsios.betterpixelmon.storage;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import com.pippohsios.betterpixelmon.BetterPixelmon;

public class PokemonStorage {
	public static final String BULBASAUR = "Bulbasaur";
	public static final String IVYSAUR = "Ivysaur";
	public static final String VENUSAUR = "Venusaur";
	public static final String CHARMANDER = "Charmander";
	public static final String CHARMELEON = "Charmeleon";
	public static final String CHARIZARD = "Charizard";
	public static final String SQUIRTLE = "Squirtle";
	public static final String WARTORTLE = "Wartortle";
	public static final String BLASTOISE = "Blastoise";
	public static final String CATERPIE = "Caterpie";
	public static final String METAPOD = "Metapod";
	public static final String BUTTERFREE = "Butterfree";
	public static final String WEEDLE = "Weedle";
	public static final String KAKUNA = "Kakuna";
	public static final String BEEDRILL = "Beedrill";
	public static final String PIDGEY = "Pidgey";
	public static final String PIDGEOTTO = "Pidgeotto";
	public static final String PIDGEOT = "Pidgeot";
	public static final String RATTATA = "Rattata";
	public static final String RATICATE = "Raticate";
	public static final String SPEAROW = "Spearow";
	public static final String FEAROW = "Fearow";
	public static final String EKANS = "Ekans";
	public static final String ARBOK = "Arbok";
	public static final String PIKACHU = "Pikachu";
	public static final String RAICHU = "Raichu";
	public static final String SANDSHREW = "Sandshrew";
	public static final String SANDSLASH = "Sandslash";
	public static final String NIDORANFEMALE = "Nidoranfemale";
	public static final String NIDORINA = "Nidorina";
	public static final String NIDOQUEEN = "Nidoqueen";
	public static final String NIDORANMALE = "Nidoranmale";
	public static final String NIDORINO = "Nidorino";
	public static final String NIDOKING = "Nidoking";
	public static final String CLEFAIRY = "Clefairy";
	public static final String CLEFABLE = "Clefable";
	public static final String VULPIX = "Vulpix";
	public static final String NINETALES = "Ninetales";
	public static final String JIGGLYPUFF = "Jigglypuff";
	public static final String WIGGLYTUFF = "Wigglytuff";
	public static final String ZUBAT = "Zubat";
	public static final String GOLBAT = "Golbat";
	public static final String ODDISH = "Oddish";
	public static final String GLOOM = "Gloom";
	public static final String VILEPLUME = "Vileplume";
	public static final String PARAS = "Paras";
	public static final String PARASECT = "Parasect";
	public static final String VENONAT = "Venonat";
	public static final String VENOMOTH = "Venomoth";
	public static final String DIGLETT = "Diglett";
	public static final String DUGTRIO = "Dugtrio";
	public static final String MEOWTH = "Meowth";
	public static final String PERSIAN = "Persian";
	public static final String PSYDUCK = "Psyduck";
	public static final String GOLDUCK = "Golduck";
	public static final String MANKEY = "Mankey";
	public static final String PRIMEAPE = "Primeape";
	public static final String GROWLITHE = "Growlithe";
	public static final String ARCANINE = "Arcanine";
	public static final String POLIWAG = "Poliwag";
	public static final String POLIWHIRL = "Poliwhirl";
	public static final String POLIWRATH = "Poliwrath";
	public static final String ABRA = "Abra";
	public static final String KADABRA = "Kadabra";
	public static final String ALAKAZAM = "Alakazam";
	public static final String MACHOP = "Machop";
	public static final String MACHOKE = "Machoke";
	public static final String MACHAMP = "Machamp";
	public static final String BELLSPROUT = "Bellsprout";
	public static final String WEEPINBELL = "Weepinbell";
	public static final String VICTREEBEL = "Victreebel";
	public static final String TENTACOOL = "Tentacool";
	public static final String TENTACRUEL = "Tentacruel";
	public static final String GEODUDE = "Geodude";
	public static final String GRAVELER = "Graveler";
	public static final String GOLEM = "Golem";
	public static final String PONYTA = "Ponyta";
	public static final String RAPIDASH = "Rapidash";
	public static final String SLOWPOKE = "Slowpoke";
	public static final String SLOWBRO = "Slowbro";
	public static final String MAGNEMITE = "Magnemite";
	public static final String MAGNETON = "Magneton";
	public static final String FARFETCHD = "Farfetchd";
	public static final String DODUO = "Doduo";
	public static final String DODRIO = "Dodrio";
	public static final String SEEL = "Seel";
	public static final String DEWGONG = "Dewgong";
	public static final String GRIMER = "Grimer";
	public static final String MUK = "Muk";
	public static final String SHELLDER = "Shellder";
	public static final String CLOYSTER = "Cloyster";
	public static final String GASTLY = "Gastly";
	public static final String HAUNTER = "Haunter";
	public static final String GENGAR = "Gengar";
	public static final String ONIX = "Onix";
	public static final String DROWZEE = "Drowzee";
	public static final String HYPNO = "Hypno";
	public static final String KRABBY = "Krabby";
	public static final String KINGLER = "Kingler";
	public static final String VOLTORB = "Voltorb";
	public static final String ELECTRODE = "Electrode";
	public static final String EXEGGCUTE = "Exeggcute";
	public static final String EXEGGUTOR = "Exeggutor";
	public static final String CUBONE = "Cubone";
	public static final String MAROWAK = "Marowak";
	public static final String HITMONLEE = "Hitmonlee";
	public static final String HITMONCHAN = "Hitmonchan";
	public static final String LICKITUNG = "Lickitung";
	public static final String KOFFING = "Koffing";
	public static final String WEEZING = "Weezing";
	public static final String RHYHORN = "Rhyhorn";
	public static final String RHYDON = "Rhydon";
	public static final String CHANSEY = "Chansey";
	public static final String TANGELA = "Tangela";
	public static final String KANGASKHAN = "Kangaskhan";
	public static final String HORSEA = "Horsea";
	public static final String SEADRA = "Seadra";
	public static final String GOLDEEN = "Goldeen";
	public static final String SEAKING = "Seaking";
	public static final String STARYU = "Staryu";
	public static final String STARMIE = "Starmie";
	public static final String MRMIME = "MrMime";
	public static final String SCYTHER = "Scyther";
	public static final String JYNX = "Jynx";
	public static final String ELECTABUZZ = "Electabuzz";
	public static final String MAGMAR = "Magmar";
	public static final String PINSIR = "Pinsir";
	public static final String TAUROS = "Tauros";
	public static final String MAGIKARP = "Magikarp";
	public static final String GYARADOS = "Gyarados";
	public static final String LAPRAS = "Lapras";
	public static final String DITTO = "Ditto";
	public static final String EEVEE = "Eevee";
	public static final String VAPOREON = "Vaporeon";
	public static final String JOLTEON = "Jolteon";
	public static final String FLAREON = "Flareon";
	public static final String PORYGON = "Porygon";
	public static final String OMANYTE = "Omanyte";
	public static final String OMASTAR = "Omastar";
	public static final String KABUTO = "Kabuto";
	public static final String KABUTOPS = "Kabutops";
	public static final String AERODACTYL = "Aerodactyl";
	public static final String SNORLAX = "Snorlax";
	public static final String ARTICUNO = "Articuno";
	public static final String ZAPDOS = "Zapdos";
	public static final String MOLTRES = "Moltres";
	public static final String DRATINI = "Dratini";
	public static final String DRAGONAIR = "Dragonair";
	public static final String DRAGONITE = "Dragonite";
	public static final String MEWTWO = "Mewtwo";
	public static final String MEW = "Mew";
	public static final String CHIKORITA = "Chikorita";
	public static final String BAYLEEF = "Bayleef";
	public static final String MEGANIUM = "Meganium";
	public static final String CYNDAQUIL = "Cyndaquil";
	public static final String QUILAVA = "Quilava";
	public static final String TYPHLOSION = "Typhlosion";
	public static final String TOTODILE = "Totodile";
	public static final String CROCONAW = "Croconaw";
	public static final String FERALIGATR = "Feraligatr";
	public static final String SENTRET = "Sentret";
	public static final String FURRET = "Furret";
	public static final String HOOTHOOT = "Hoothoot";
	public static final String NOCTOWL = "Noctowl";
	public static final String LEDYBA = "Ledyba";
	public static final String LEDIAN = "Ledian";
	public static final String SPINARAK = "Spinarak";
	public static final String ARIADOS = "Ariados";
	public static final String CROBAT = "Crobat";
	public static final String CHINCHOU = "Chinchou";
	public static final String LANTURN = "Lanturn";
	public static final String PICHU = "Pichu";
	public static final String CLEFFA = "Cleffa";
	public static final String IGGLYBUFF = "Igglybuff";
	public static final String TOGEPI = "Togepi";
	public static final String TOGETIC = "Togetic";
	public static final String NATU = "Natu";
	public static final String XATU = "Xatu";
	public static final String MAREEP = "Mareep";
	public static final String FLAAFFY = "Flaaffy";
	public static final String AMPHAROS = "Ampharos";
	public static final String BELLOSSOM = "Bellossom";
	public static final String MARILL = "Marill";
	public static final String AZUMARILL = "Azumarill";
	public static final String SUDOWOODO = "Sudowoodo";
	public static final String POLITOED = "Politoed";
	public static final String HOPPIP = "Hoppip";
	public static final String SKIPLOOM = "Skiploom";
	public static final String JUMPLUFF = "Jumpluff";
	public static final String AIPOM = "Aipom";
	public static final String SUNKERN = "Sunkern";
	public static final String SUNFLORA = "Sunflora";
	public static final String YANMA = "Yanma";
	public static final String WOOPER = "Wooper";
	public static final String QUAGSIRE = "Quagsire";
	public static final String ESPEON = "Espeon";
	public static final String UMBREON = "Umbreon";
	public static final String MURKROW = "Murkrow";
	public static final String SLOWKING = "Slowking";
	public static final String MISDREAVUS = "Misdreavus";
	public static final String UNOWN = "Unown";
	public static final String WOBBUFFET = "Wobbuffet";
	public static final String GIRAFARIG = "Girafarig";
	public static final String PINECO = "Pineco";
	public static final String FORRETRESS = "Forretress";
	public static final String DUNSPARCE = "Dunsparce";
	public static final String GLIGAR = "Gligar";
	public static final String STEELIX = "Steelix";
	public static final String SNUBBULL = "Snubbull";
	public static final String GRANBULL = "Granbull";
	public static final String QWILFISH = "Qwilfish";
	public static final String SCIZOR = "Scizor";
	public static final String SHUCKLE = "Shuckle";
	public static final String HERACROSS = "Heracross";
	public static final String SNEASEL = "Sneasel";
	public static final String TEDDIURSA = "Teddiursa";
	public static final String URSARING = "Ursaring";
	public static final String SLUGMA = "Slugma";
	public static final String MAGCARGO = "Magcargo";
	public static final String SWINUB = "Swinub";
	public static final String PILOSWINE = "Piloswine";
	public static final String CORSOLA = "Corsola";
	public static final String REMORAID = "Remoraid";
	public static final String OCTILLERY = "Octillery";
	public static final String DELIBIRD = "Delibird";
	public static final String MANTINE = "Mantine";
	public static final String SKARMORY = "Skarmory";
	public static final String HOUNDOUR = "Houndour";
	public static final String HOUNDOOM = "Houndoom";
	public static final String KINGDRA = "Kingdra";
	public static final String PHANPY = "Phanpy";
	public static final String DONPHAN = "Donphan";
	public static final String PORYGON2 = "Porygon2";
	public static final String STANTLER = "Stantler";
	public static final String SMEARGLE = "Smeargle";
	public static final String TYROGUE = "Tyrogue";
	public static final String HITMONTOP = "Hitmontop";
	public static final String SMOOCHUM = "Smoochum";
	public static final String ELEKID = "Elekid";
	public static final String MAGBY = "Magby";
	public static final String MILTANK = "Miltank";
	public static final String BLISSEY = "Blissey";
	public static final String RAIKOU = "Raikou";
	public static final String ENTEI = "Entei";
	public static final String SUICUNE = "Suicune";
	public static final String LARVITAR = "Larvitar";
	public static final String PUPITAR = "Pupitar";
	public static final String TYRANITAR = "Tyranitar";
	public static final String LUGIA = "Lugia";
	public static final String HOOH = "Hooh";
	public static final String CELEBI = "Celebi";
	public static final String TREECKO = "Treecko";
	public static final String GROVYLE = "Grovyle";
	public static final String SCEPTILE = "Sceptile";
	public static final String TORCHIC = "Torchic";
	public static final String COMBUSKEN = "Combusken";
	public static final String BLAZIKEN = "Blaziken";
	public static final String MUDKIP = "Mudkip";
	public static final String MARSHTOMP = "Marshtomp";
	public static final String SWAMPERT = "Swampert";
	public static final String POOCHYENA = "Poochyena";
	public static final String MIGHTYENA = "Mightyena";
	public static final String ZIGZAGOON = "Zigzagoon";
	public static final String LINOONE = "Linoone";
	public static final String WURMPLE = "Wurmple";
	public static final String SILCOON = "Silcoon";
	public static final String BEAUTIFLY = "Beautifly";
	public static final String CASCOON = "Cascoon";
	public static final String DUSTOX = "Dustox";
	public static final String LOTAD = "Lotad";
	public static final String LOMBRE = "Lombre";
	public static final String LUDICOLO = "Ludicolo";
	public static final String SEEDOT = "Seedot";
	public static final String NUZLEAF = "Nuzleaf";
	public static final String SHIFTRY = "Shiftry";
	public static final String TAILLOW = "Taillow";
	public static final String SWELLOW = "Swellow";
	public static final String WINGULL = "Wingull";
	public static final String PELIPPER = "Pelipper";
	public static final String RALTS = "Ralts";
	public static final String KIRLIA = "Kirlia";
	public static final String GARDEVOIR = "Gardevoir";
	public static final String SURSKIT = "Surskit";
	public static final String MASQUERAIN = "Masquerain";
	public static final String SHROOMISH = "Shroomish";
	public static final String BRELOOM = "Breloom";
	public static final String SLAKOTH = "Slakoth";
	public static final String VIGOROTH = "Vigoroth";
	public static final String SLAKING = "Slaking";
	public static final String NINCADA = "Nincada";
	public static final String NINJASK = "Ninjask";
	public static final String SHEDINJA = "Shedinja";
	public static final String WHISMUR = "Whismur";
	public static final String LOUDRED = "Loudred";
	public static final String EXPLOUD = "Exploud";
	public static final String MAKUHITA = "Makuhita";
	public static final String HARIYAMA = "Hariyama";
	public static final String AZURILL = "Azurill";
	public static final String NOSEPASS = "Nosepass";
	public static final String SKITTY = "Skitty";
	public static final String DELCATTY = "Delcatty";
	public static final String SABLEYE = "Sableye";
	public static final String MAWILE = "Mawile";
	public static final String ARON = "Aron";
	public static final String LAIRON = "Lairon";
	public static final String AGGRON = "Aggron";
	public static final String MEDITITE = "Meditite";
	public static final String MEDICHAM = "Medicham";
	public static final String ELECTRIKE = "Electrike";
	public static final String MANECTRIC = "Manectric";
	public static final String PLUSLE = "Plusle";
	public static final String MINUN = "Minun";
	public static final String VOLBEAT = "Volbeat";
	public static final String ILLUMISE = "Illumise";
	public static final String ROSELIA = "Roselia";
	public static final String GULPIN = "Gulpin";
	public static final String SWALOT = "Swalot";
	public static final String CARVANHA = "Carvanha";
	public static final String SHARPEDO = "Sharpedo";
	public static final String WAILMER = "Wailmer";
	public static final String WAILORD = "Wailord";
	public static final String NUMEL = "Numel";
	public static final String CAMERUPT = "Camerupt";
	public static final String TORKOAL = "Torkoal";
	public static final String SPOINK = "Spoink";
	public static final String GRUMPIG = "Grumpig";
	public static final String SPINDA = "Spinda";
	public static final String TRAPINCH = "Trapinch";
	public static final String VIBRAVA = "Vibrava";
	public static final String FLYGON = "Flygon";
	public static final String CACNEA = "Cacnea";
	public static final String CACTURNE = "Cacturne";
	public static final String SWABLU = "Swablu";
	public static final String ALTARIA = "Altaria";
	public static final String ZANGOOSE = "Zangoose";
	public static final String SEVIPER = "Seviper";
	public static final String LUNATONE = "Lunatone";
	public static final String SOLROCK = "Solrock";
	public static final String BARBOACH = "Barboach";
	public static final String WHISCASH = "Whiscash";
	public static final String CORPHISH = "Corphish";
	public static final String CRAWDAUNT = "Crawdaunt";
	public static final String BALTOY = "Baltoy";
	public static final String CLAYDOL = "Claydol";
	public static final String LILEEP = "Lileep";
	public static final String CRADILY = "Cradily";
	public static final String ANORITH = "Anorith";
	public static final String ARMALDO = "Armaldo";
	public static final String FEEBAS = "Feebas";
	public static final String MILOTIC = "Milotic";
	public static final String CASTFORM = "Castform";
	public static final String KECLEON = "Kecleon";
	public static final String SHUPPET = "Shuppet";
	public static final String BANETTE = "Banette";
	public static final String DUSKULL = "Duskull";
	public static final String DUSCLOPS = "Dusclops";
	public static final String TROPIUS = "Tropius";
	public static final String CHIMECHO = "Chimecho";
	public static final String ABSOL = "Absol";
	public static final String WYNAUT = "Wynaut";
	public static final String SNORUNT = "Snorunt";
	public static final String GLALIE = "Glalie";
	public static final String SPHEAL = "Spheal";
	public static final String SEALEO = "Sealeo";
	public static final String WALREIN = "Walrein";
	public static final String CLAMPERL = "Clamperl";
	public static final String HUNTAIL = "Huntail";
	public static final String GOREBYSS = "Gorebyss";
	public static final String RELICANTH = "Relicanth";
	public static final String LUVDISC = "Luvdisc";
	public static final String BAGON = "Bagon";
	public static final String SHELGON = "Shelgon";
	public static final String SALAMENCE = "Salamence";
	public static final String BELDUM = "Beldum";
	public static final String METANG = "Metang";
	public static final String METAGROSS = "Metagross";
	public static final String REGIROCK = "Regirock";
	public static final String REGICE = "Regice";
	public static final String REGISTEEL = "Registeel";
	public static final String LATIAS = "Latias";
	public static final String LATIOS = "Latios";
	public static final String KYOGRE = "Kyogre";
	public static final String GROUDON = "Groudon";
	public static final String RAYQUAZA = "Rayquaza";
	public static final String JIRACHI = "Jirachi";
	public static final String DEOXYS = "Deoxys";
	public static final String TURTWIG = "Turtwig";
	public static final String GROTLE = "Grotle";
	public static final String TORTERRA = "Torterra";
	public static final String CHIMCHAR = "Chimchar";
	public static final String MONFERNO = "Monferno";
	public static final String INFERNAPE = "Infernape";
	public static final String PIPLUP = "Piplup";
	public static final String PRINPLUP = "Prinplup";
	public static final String EMPOLEON = "Empoleon";
	public static final String STARLY = "Starly";
	public static final String STARAVIA = "Staravia";
	public static final String STARAPTOR = "Staraptor";
	public static final String BIDOOF = "Bidoof";
	public static final String BIBAREL = "Bibarel";
	public static final String KRICKETOT = "Kricketot";
	public static final String KRICKETUNE = "Kricketune";
	public static final String SHINX = "Shinx";
	public static final String LUXIO = "Luxio";
	public static final String LUXRAY = "Luxray";
	public static final String BUDEW = "Budew";
	public static final String ROSERADE = "Roserade";
	public static final String CRANIDOS = "Cranidos";
	public static final String RAMPARDOS = "Rampardos";
	public static final String SHIELDON = "Shieldon";
	public static final String BASTIODON = "Bastiodon";
	public static final String BURMY = "Burmy";
	public static final String WORMADAM = "Wormadam";
	public static final String MOTHIM = "Mothim";
	public static final String COMBEE = "Combee";
	public static final String VESPIQUEN = "Vespiquen";
	public static final String PACHIRISU = "Pachirisu";
	public static final String BUIZEL = "Buizel";
	public static final String FLOATZEL = "Floatzel";
	public static final String CHERUBI = "Cherubi";
	public static final String CHERRIM = "Cherrim";
	public static final String SHELLOS = "Shellos";
	public static final String GASTRODON = "Gastrodon";
	public static final String AMBIPOM = "Ambipom";
	public static final String DRIFLOON = "Drifloon";
	public static final String DRIFBLIM = "Drifblim";
	public static final String BUNEARY = "Buneary";
	public static final String LOPUNNY = "Lopunny";
	public static final String MISMAGIUS = "Mismagius";
	public static final String HONCHKROW = "Honchkrow";
	public static final String GLAMEOW = "Glameow";
	public static final String PURUGLY = "Purugly";
	public static final String CHINGLING = "Chingling";
	public static final String STUNKY = "Stunky";
	public static final String SKUNTANK = "Skuntank";
	public static final String BRONZOR = "Bronzor";
	public static final String BRONZONG = "Bronzong";
	public static final String BONSLY = "Bonsly";
	public static final String MIMEJR = "MimeJr";
	public static final String HAPPINY = "Happiny";
	public static final String CHATOT = "Chatot";
	public static final String SPIRITOMB = "Spiritomb";
	public static final String GIBLE = "Gible";
	public static final String GABITE = "Gabite";
	public static final String GARCHOMP = "Garchomp";
	public static final String MUNCHLAX = "Munchlax";
	public static final String RIOLU = "Riolu";
	public static final String LUCARIO = "Lucario";
	public static final String HIPPOPOTAS = "Hippopotas";
	public static final String HIPPOWDON = "Hippowdon";
	public static final String SKORUPI = "Skorupi";
	public static final String DRAPION = "Drapion";
	public static final String CROAGUNK = "Croagunk";
	public static final String TOXICROAK = "Toxicroak";
	public static final String CARNIVINE = "Carnivine";
	public static final String FINNEON = "Finneon";
	public static final String LUMINEON = "Lumineon";
	public static final String MANTYKE = "Mantyke";
	public static final String SNOVER = "Snover";
	public static final String ABOMASNOW = "Abomasnow";
	public static final String WEAVILE = "Weavile";
	public static final String MAGNEZONE = "Magnezone";
	public static final String LICKILICKY = "Lickilicky";
	public static final String RHYPERIOR = "Rhyperior";
	public static final String TANGROWTH = "Tangrowth";
	public static final String ELECTIVIRE = "Electivire";
	public static final String MAGMORTAR = "Magmortar";
	public static final String TOGEKISS = "Togekiss";
	public static final String YANMEGA = "Yanmega";
	public static final String LEAFEON = "Leafeon";
	public static final String GLACEON = "Glaceon";
	public static final String GLISCOR = "Gliscor";
	public static final String MAMOSWINE = "Mamoswine";
	public static final String PORYGONZ = "Porygon-Z";
	public static final String GALLADE = "Gallade";
	public static final String PROBOPASS = "Probopass";
	public static final String DUSKNOIR = "Dusknoir";
	public static final String FROSLASS = "Froslass";
	public static final String ROTOM = "Rotom";
	public static final String UXIE = "Uxie";
	public static final String MESPRIT = "Mesprit";
	public static final String AZELF = "Azelf";
	public static final String DIALGA = "Dialga";
	public static final String PALKIA = "Palkia";
	public static final String HEATRAN = "Heatran";
	public static final String REGIGIGAS = "Regigigas";
	public static final String GIRATINA = "Giratina";
	public static final String CRESSELIA = "Cresselia";
	public static final String PHIONE = "Phione";
	public static final String MANAPHY = "Manaphy";
	public static final String DARKRAI = "Darkrai";
	public static final String SHAYMIN = "Shaymin";
	public static final String ARCEUS = "Arceus";
	public static final String VICTINI = "Victini";
	public static final String SNIVY = "Snivy";
	public static final String SERVINE = "Servine";
	public static final String SERPERIOR = "Serperior";
	public static final String TEPIG = "Tepig";
	public static final String PIGNITE = "Pignite";
	public static final String EMBOAR = "Emboar";
	public static final String OSHAWOTT = "Oshawott";
	public static final String DEWOTT = "Dewott";
	public static final String SAMUROTT = "Samurott";
	public static final String PATRAT = "Patrat";
	public static final String WATCHOG = "Watchog";
	public static final String LILLIPUP = "Lillipup";
	public static final String HERDIER = "Herdier";
	public static final String STOUTLAND = "Stoutland";
	public static final String PURRLOIN = "Purrloin";
	public static final String LIEPARD = "Liepard";
	public static final String PANSAGE = "Pansage";
	public static final String SIMISAGE = "Simisage";
	public static final String PANSEAR = "Pansear";
	public static final String SIMISEAR = "Simisear";
	public static final String PANPOUR = "Panpour";
	public static final String SIMIPOUR = "Simipour";
	public static final String MUNNA = "Munna";
	public static final String MUSHARNA = "Musharna";
	public static final String PIDOVE = "Pidove";
	public static final String TRANQUILL = "Tranquill";
	public static final String UNFEZANT = "Unfezant";
	public static final String BLITZLE = "Blitzle";
	public static final String ZEBSTRIKA = "Zebstrika";
	public static final String ROGGENROLA = "Roggenrola";
	public static final String BOLDORE = "Boldore";
	public static final String GIGALITH = "Gigalith";
	public static final String WOOBAT = "Woobat";
	public static final String SWOOBAT = "Swoobat";
	public static final String DRILBUR = "Drilbur";
	public static final String EXCADRILL = "Excadrill";
	public static final String AUDINO = "Audino";
	public static final String TIMBURR = "Timburr";
	public static final String GURDURR = "Gurdurr";
	public static final String CONKELDURR = "Conkeldurr";
	public static final String TYMPOLE = "Tympole";
	public static final String PALPITOAD = "Palpitoad";
	public static final String SEISMITOAD = "Seismitoad";
	public static final String THROH = "Throh";
	public static final String SAWK = "Sawk";
	public static final String SEWADDLE = "Sewaddle";
	public static final String SWADLOON = "Swadloon";
	public static final String LEAVANNY = "Leavanny";
	public static final String VENIPEDE = "Venipede";
	public static final String WHIRLIPEDE = "Whirlipede";
	public static final String SCOLIPEDE = "Scolipede";
	public static final String COTTONEE = "Cottonee";
	public static final String WHIMSICOTT = "Whimsicott";
	public static final String PETILIL = "Petilil";
	public static final String LILLIGANT = "Lilligant";
	public static final String BASCULIN = "Basculin";
	public static final String SANDILE = "Sandile";
	public static final String KROKOROK = "Krokorok";
	public static final String KROOKODILE = "Krookodile";
	public static final String DARUMAKA = "Darumaka";
	public static final String DARMANITAN = "Darmanitan";
	public static final String MARACTUS = "Maractus";
	public static final String DWEBBLE = "Dwebble";
	public static final String CRUSTLE = "Crustle";
	public static final String SCRAGGY = "Scraggy";
	public static final String SCRAFTY = "Scrafty";
	public static final String SIGILYPH = "Sigilyph";
	public static final String YAMASK = "Yamask";
	public static final String COFAGRIGUS = "Cofagrigus";
	public static final String TIRTOUGA = "Tirtouga";
	public static final String CARRACOSTA = "Carracosta";
	public static final String ARCHEN = "Archen";
	public static final String ARCHEOPS = "Archeops";
	public static final String TRUBBISH = "Trubbish";
	public static final String GARBODOR = "Garbodor";
	public static final String ZORUA = "Zorua";
	public static final String ZOROARK = "Zoroark";
	public static final String MINCCINO = "Minccino";
	public static final String CINCCINO = "Cinccino";
	public static final String GOTHITA = "Gothita";
	public static final String GOTHORITA = "Gothorita";
	public static final String GOTHITELLE = "Gothitelle";
	public static final String SOLOSIS = "Solosis";
	public static final String DUOSION = "Duosion";
	public static final String REUNICLUS = "Reuniclus";
	public static final String DUCKLETT = "Ducklett";
	public static final String SWANNA = "Swanna";
	public static final String VANILLITE = "Vanillite";
	public static final String VANILLISH = "Vanillish";
	public static final String VANILLUXE = "Vanilluxe";
	public static final String DEERLING = "Deerling";
	public static final String SAWSBUCK = "Sawsbuck";
	public static final String EMOLGA = "Emolga";
	public static final String KARRABLAST = "Karrablast";
	public static final String ESCAVALIER = "Escavalier";
	public static final String FOONGUS = "Foongus";
	public static final String AMOONGUSS = "Amoonguss";
	public static final String FRILLISH = "Frillish";
	public static final String JELLICENT = "Jellicent";
	public static final String ALOMOMOLA = "Alomomola";
	public static final String JOLTIK = "Joltik";
	public static final String GALVANTULA = "Galvantula";
	public static final String FERROSEED = "Ferroseed";
	public static final String FERROTHORN = "Ferrothorn";
	public static final String KLINK = "Klink";
	public static final String KLANG = "Klang";
	public static final String KLINKLANG = "Klinklang";
	public static final String TYNAMO = "Tynamo";
	public static final String EELEKTRIK = "Eelektrik";
	public static final String EELEKTROSS = "Eelektross";
	public static final String ELGYEM = "Elgyem";
	public static final String BEHEEYEM = "Beheeyem";
	public static final String LITWICK = "Litwick";
	public static final String LAMPENT = "Lampent";
	public static final String CHANDELURE = "Chandelure";
	public static final String AXEW = "Axew";
	public static final String FRAXURE = "Fraxure";
	public static final String HAXORUS = "Haxorus";
	public static final String CUBCHOO = "Cubchoo";
	public static final String BEARTIC = "Beartic";
	public static final String CRYOGONAL = "Cryogonal";
	public static final String SHELMET = "Shelmet";
	public static final String ACCELGOR = "Accelgor";
	public static final String STUNFISK = "Stunfisk";
	public static final String MIENFOO = "Mienfoo";
	public static final String MIENSHAO = "Mienshao";
	public static final String DRUDDIGON = "Druddigon";
	public static final String GOLETT = "Golett";
	public static final String GOLURK = "Golurk";
	public static final String PAWNIARD = "Pawniard";
	public static final String BISHARP = "Bisharp";
	public static final String BOUFFALANT = "Bouffalant";
	public static final String RUFFLET = "Rufflet";
	public static final String BRAVIARY = "Braviary";
	public static final String VULLABY = "Vullaby";
	public static final String MANDIBUZZ = "Mandibuzz";
	public static final String HEATMOR = "Heatmor";
	public static final String DURANT = "Durant";
	public static final String DEINO = "Deino";
	public static final String ZWEILOUS = "Zweilous";
	public static final String HYDREIGON = "Hydreigon";
	public static final String LARVESTA = "Larvesta";
	public static final String VOLCARONA = "Volcarona";
	public static final String COBALION = "Cobalion";
	public static final String TERRAKION = "Terrakion";
	public static final String VIRIZION = "Virizion";
	public static final String TORNADUS = "Tornadus";
	public static final String THUNDURUS = "Thundurus";
	public static final String RESHIRAM = "Reshiram";
	public static final String ZEKROM = "Zekrom";
	public static final String LANDORUS = "Landorus";
	public static final String KYUREM = "Kyurem";
	public static final String KELDEO = "Keldeo";
	public static final String MELOETTA = "Meloetta";
	public static final String GENESECT = "Genesect";
	public static final String CHESPIN = "Chespin";
	public static final String QUILLADIN = "Quilladin";
	public static final String CHESNAUGHT = "Chesnaught";
	public static final String FENNEKIN = "Fennekin";
	public static final String BRAIXEN = "Braixen";
	public static final String DELPHOX = "Delphox";
	public static final String FROAKIE = "Froakie";
	public static final String FROGADIER = "Frogadier";
	public static final String GRENINJA = "Greninja";
	public static final String BUNNELBY = "Bunnelby";
	public static final String DIGGERSBY = "Diggersby";
	public static final String FLETCHLING = "Fletchling";
	public static final String FLETCHINDER = "Fletchinder";
	public static final String TALONFLAME = "Talonflame";
	public static final String SCATTERBUG = "Scatterbug";
	public static final String SPEWPA = "Spewpa";
	public static final String VIVILLON = "Vivillon";
	public static final String LITLEO = "Litleo";
	public static final String PYROAR = "Pyroar";
	public static final String FLABEBE = "Flabebe";
	public static final String FLOETTE = "Floette";
	public static final String FLORGES = "Florges";
	public static final String SKIDDO = "Skiddo";
	public static final String GOGOAT = "Gogoat";
	public static final String PANCHAM = "Pancham";
	public static final String PANGORO = "Pangoro";
	public static final String FURFROU = "Furfrou";
	public static final String ESPURR = "Espurr";
	public static final String MEOWSTIC = "Meowstic";
	public static final String HONEDGE = "Honedge";
	public static final String DOUBLADE = "Doublade";
	public static final String AEGISLASH = "Aegislash";
	public static final String SPRITZEE = "Spritzee";
	public static final String AROMATISSE = "Aromatisse";
	public static final String SWIRLIX = "Swirlix";
	public static final String SLURPUFF = "Slurpuff";
	public static final String INKAY = "Inkay";
	public static final String MALAMAR = "Malamar";
	public static final String BINACLE = "Binacle";
	public static final String BARBARACLE = "Barbaracle";
	public static final String SKRELP = "Skrelp";
	public static final String DRAGALGE = "Dragalge";
	public static final String CLAUNCHER = "Clauncher";
	public static final String CLAWITZER = "Clawitzer";
	public static final String HELIOPTILE = "Helioptile";
	public static final String HELIOLISK = "Heliolisk";
	public static final String TYRUNT = "Tyrunt";
	public static final String TYRANTRUM = "Tyrantrum";
	public static final String AMAURA = "Amaura";
	public static final String AURORUS = "Aurorus";
	public static final String SYLVEON = "Sylveon";
	public static final String HAWLUCHA = "Hawlucha";
	public static final String DEDENNE = "Dedenne";
	public static final String CARBINK = "Carbink";
	public static final String GOOMY = "Goomy";
	public static final String SLIGGOO = "Sliggoo";
	public static final String GOODRA = "Goodra";
	public static final String KLEFKI = "Klefki";
	public static final String PHANTUMP = "Phantump";
	public static final String TREVENANT = "Trevenant";
	public static final String PUMPKABOO = "Pumpkaboo";
	public static final String GOURGEIST = "Gourgeist";
	public static final String BERGMITE = "Bergmite";
	public static final String AVALUGG = "Avalugg";
	public static final String NOIBAT = "Noibat";
	public static final String NOIVERN = "Noivern";
	public static final String XERNEAS = "Xerneas";
	public static final String YVELTAL = "Yveltal";
	public static final String ZYGARDE = "Zygarde";
	public static final String DIANCIE = "Diancie";
	public static final String HOOPA = "Hoopa";
	public static final String VOLCANION = "Volcanion";
	public static final String ROWLET = "Rowlet";
	public static final String DARTRIX = "Dartrix";
	public static final String DECIDUEYE = "Decidueye";
	public static final String LITTEN = "Litten";
	public static final String TORRACAT = "Torracat";
	public static final String INCINEROAR = "Incineroar";
	public static final String POPPLIO = "Popplio";
	public static final String BRIONNE = "Brionne";
	public static final String PRIMARINA = "Primarina";
	public static final String PIKIPEK = "Pikipek";
	public static final String TRUMBEAK = "Trumbeak";
	public static final String TOUCANNON = "Toucannon";
	public static final String YUNGOOS = "Yungoos";
	public static final String GUMSHOOS = "Gumshoos";
	public static final String GRUBBIN = "Grubbin";
	public static final String CHARJABUG = "Charjabug";
	public static final String VIKAVOLT = "Vikavolt";
	public static final String CRABRAWLER = "Crabrawler";
	public static final String CRABOMINABLE = "Crabominable";
	public static final String ORICORIO = "Oricorio";
	public static final String CUTIEFLY = "Cutiefly";
	public static final String RIBOMBEE = "Ribombee";
	public static final String ROCKRUFF = "Rockruff";
	public static final String LYCANROC = "Lycanroc";
	public static final String WISHIWASHI = "Wishiwashi";
	public static final String MAREANIE = "Mareanie";
	public static final String TOXAPEX = "Toxapex";
	public static final String MUDBRAY = "Mudbray";
	public static final String MUDSDALE = "Mudsdale";
	public static final String DEWPIDER = "Dewpider";
	public static final String ARAQUANID = "Araquanid";
	public static final String FOMANTIS = "Fomantis";
	public static final String LURANTIS = "Lurantis";
	public static final String MORELULL = "Morelull";
	public static final String SHIINOTIC = "Shiinotic";
	public static final String SALANDIT = "Salandit";
	public static final String SALAZZLE = "Salazzle";
	public static final String STUFFUL = "Stufful";
	public static final String BEWEAR = "Bewear";
	public static final String BOUNSWEET = "Bounsweet";
	public static final String STEENEE = "Steenee";
	public static final String TSAREENA = "Tsareena";
	public static final String COMFEY = "Comfey";
	public static final String ORANGURU = "Oranguru";
	public static final String PASSIMIAN = "Passimian";
	public static final String WIMPOD = "Wimpod";
	public static final String GOLISOPOD = "Golisopod";
	public static final String SANDYGAST = "Sandygast";
	public static final String PALOSSAND = "Palossand";
	public static final String PYUKUMUKU = "Pyukumuku";
	public static final String TYPENULL = "TypeNull";
	public static final String SILVALLY = "Silvally";
	public static final String MINIOR = "Minior";
	public static final String KOMALA = "Komala";
	public static final String TURTONATOR = "Turtonator";
	public static final String TOGEDEMARU = "Togedemaru";
	public static final String MIMIKYU = "Mimikyu";
	public static final String BRUXISH = "Bruxish";
	public static final String DRAMPA = "Drampa";
	public static final String DHELMISE = "Dhelmise";
	public static final String JANGMOO = "Jangmoo";
	public static final String HAKAMOO = "Hakamoo";
	public static final String KOMMOO = "Kommoo";
	public static final String TAPU_KOKO = "Tapu_Koko";
	public static final String TAPU_LELE = "Tapu_Lele";
	public static final String TAPU_BULU = "Tapu_Bulu";
	public static final String TAPU_FINI = "Tapu_Fini";
	public static final String COSMOG = "Cosmog";
	public static final String COSMOEM = "Cosmoem";
	public static final String SOLGALEO = "Solgaleo";
	public static final String LUNALA = "Lunala";
	public static final String NIHILEGO = "Nihilego";
	public static final String BUZZWOLE = "Buzzwole";
	public static final String PHEROMOSA = "Pheromosa";
	public static final String XURKITREE = "Xurkitree";
	public static final String CELESTEELA = "Celesteela";
	public static final String KARTANA = "Kartana";
	public static final String GUZZLORD = "Guzzlord";
	public static final String NECROZMA = "Necrozma";
	public static final String MAGEARNA = "Magearna";
	public static final String MARSHADOW = "Marshadow";
	public static final String POIPOLE = "Poipole";
	public static final String NAGANADEL = "Naganadel";
	public static final String STAKATAKA = "Stakataka";
	public static final String BLACEPHALON = "Blacephalon";
	public static final String ZERAORA = "Zeraora";
	public static final String MELTAN = "Meltan";
	public static final String MELMETAL = "Melmetal";
	public static final String GROOKEY = "Grookey";
	public static final String THWACKEY = "Thwackey";
	public static final String RILLABOOM = "Rillaboom";
	public static final String SCORBUNNY = "Scorbunny";
	public static final String RABOOT = "Raboot";
	public static final String CINDERACE = "Cinderace";
	public static final String SOBBLE = "Sobble";
	public static final String DRIZZILE = "Drizzile";
	public static final String INTELEON = "Inteleon";
	public static final String SKWOVET = "Skwovet";
	public static final String GREEDENT = "Greedent";
	public static final String ROOKIDEE = "Rookidee";
	public static final String CORVISQUIRE = "Corvisquire";
	public static final String CORVIKNIGHT = "Corviknight";
	public static final String BLIPBUG = "Blipbug";
	public static final String DOTTLER = "Dottler";
	public static final String ORBEETLE = "Orbeetle";
	public static final String NICKIT = "Nickit";
	public static final String THIEVUL = "Thievul";
	public static final String GOSSIFLEUR = "Gossifleur";
	public static final String ELDEGOSS = "Eldegoss";
	public static final String WOOLOO = "Wooloo";
	public static final String DUBWOOL = "Dubwool";
	public static final String CHEWTLE = "Chewtle";
	public static final String DREDNAW = "Drednaw";
	public static final String YAMPER = "Yamper";
	public static final String BOLTUND = "Boltund";
	public static final String ROLYCOLY = "Rolycoly";
	public static final String CARKOL = "Carkol";
	public static final String COALOSSAL = "Coalossal";
	public static final String APPLIN = "Applin";
	public static final String FLAPPLE = "Flapple";
	public static final String APPLETUN = "Appletun";
	public static final String SILICOBRA = "Silicobra";
	public static final String SANDACONDA = "Sandaconda";
	public static final String CRAMORANT = "Cramorant";
	public static final String ARROKUDA = "Arrokuda";
	public static final String BARRASKEWDA = "Barraskewda";
	public static final String TOXEL = "Toxel";
	public static final String TOXTRICITY = "Toxtricity";
	public static final String SIZZLIPEDE = "Sizzlipede";
	public static final String CENTISKORCH = "Centiskorch";
	public static final String CLOBBOPUS = "Clobbopus";
	public static final String GRAPPLOCT = "Grapploct";
	public static final String SINISTEA = "Sinistea";
	public static final String POLTEAGEIST = "Polteageist";
	public static final String HATENNA = "Hatenna";
	public static final String HATTREM = "Hattrem";
	public static final String HATTERENE = "Hatterene";
	public static final String IMPIDIMP = "Impidimp";
	public static final String MORGREM = "Morgrem";
	public static final String GRIMMSNARL = "Grimmsnarl";
	public static final String OBSTAGOON = "Obstagoon";
	public static final String PERRSERKER = "Perrserker";
	public static final String CURSOLA = "Cursola";
	public static final String SIRFETCHD = "Sirfetchd";
	public static final String MRRIME = "MrRime";
	public static final String RUNERIGUS = "Runerigus";
	public static final String MILCERY = "Milcery";
	public static final String ALCREMIE = "Alcremie";
	public static final String FALINKS = "Falinks";
	public static final String PINCURCHIN = "Pincurchin";
	public static final String SNOM = "Snom";
	public static final String FROSMOTH = "Frosmoth";
	public static final String STONJOURNER = "Stonjourner";
	public static final String EISCUE = "Eiscue";
	public static final String INDEEDEE = "Indeedee";
	public static final String MORPEKO = "Morpeko";
	public static final String DREEPY = "Dreepy";
	public static final String DRAKLOAK = "Drakloak";
	public static final String DRAGAPULT = "Dragapult";

	public static List<String> pokemons = new ArrayList<String>();
	public static List<String> legendaries = new ArrayList<String>();

	public static void init() {
		BetterPixelmon.instance.logger.info("Loading pixelmon entity names");

		pokemons.add(BULBASAUR);
		pokemons.add(IVYSAUR);
		pokemons.add(VENUSAUR);
		pokemons.add(CHARMANDER);
		pokemons.add(CHARMELEON);
		pokemons.add(CHARIZARD);
		pokemons.add(SQUIRTLE);
		pokemons.add(WARTORTLE);
		pokemons.add(BLASTOISE);
		pokemons.add(CATERPIE);
		pokemons.add(METAPOD);
		pokemons.add(BUTTERFREE);
		pokemons.add(WEEDLE);
		pokemons.add(KAKUNA);
		pokemons.add(BEEDRILL);
		pokemons.add(PIDGEY);
		pokemons.add(PIDGEOTTO);
		pokemons.add(PIDGEOT);
		pokemons.add(RATTATA);
		pokemons.add(RATICATE);
		pokemons.add(SPEAROW);
		pokemons.add(FEAROW);
		pokemons.add(EKANS);
		pokemons.add(ARBOK);
		pokemons.add(PIKACHU);
		pokemons.add(RAICHU);
		pokemons.add(SANDSHREW);
		pokemons.add(SANDSLASH);
		pokemons.add(NIDORANFEMALE);
		pokemons.add(NIDORINA);
		pokemons.add(NIDOQUEEN);
		pokemons.add(NIDORANMALE);
		pokemons.add(NIDORINO);
		pokemons.add(NIDOKING);
		pokemons.add(CLEFAIRY);
		pokemons.add(CLEFABLE);
		pokemons.add(VULPIX);
		pokemons.add(NINETALES);
		pokemons.add(JIGGLYPUFF);
		pokemons.add(WIGGLYTUFF);
		pokemons.add(ZUBAT);
		pokemons.add(GOLBAT);
		pokemons.add(ODDISH);
		pokemons.add(GLOOM);
		pokemons.add(VILEPLUME);
		pokemons.add(PARAS);
		pokemons.add(PARASECT);
		pokemons.add(VENONAT);
		pokemons.add(VENOMOTH);
		pokemons.add(DIGLETT);
		pokemons.add(DUGTRIO);
		pokemons.add(MEOWTH);
		pokemons.add(PERSIAN);
		pokemons.add(PSYDUCK);
		pokemons.add(GOLDUCK);
		pokemons.add(MANKEY);
		pokemons.add(PRIMEAPE);
		pokemons.add(GROWLITHE);
		pokemons.add(ARCANINE);
		pokemons.add(POLIWAG);
		pokemons.add(POLIWHIRL);
		pokemons.add(POLIWRATH);
		pokemons.add(ABRA);
		pokemons.add(KADABRA);
		pokemons.add(ALAKAZAM);
		pokemons.add(MACHOP);
		pokemons.add(MACHOKE);
		pokemons.add(MACHAMP);
		pokemons.add(BELLSPROUT);
		pokemons.add(WEEPINBELL);
		pokemons.add(VICTREEBEL);
		pokemons.add(TENTACOOL);
		pokemons.add(TENTACRUEL);
		pokemons.add(GEODUDE);
		pokemons.add(GRAVELER);
		pokemons.add(GOLEM);
		pokemons.add(PONYTA);
		pokemons.add(RAPIDASH);
		pokemons.add(SLOWPOKE);
		pokemons.add(SLOWBRO);
		pokemons.add(MAGNEMITE);
		pokemons.add(MAGNETON);
		pokemons.add(FARFETCHD);
		pokemons.add(DODUO);
		pokemons.add(DODRIO);
		pokemons.add(SEEL);
		pokemons.add(DEWGONG);
		pokemons.add(GRIMER);
		pokemons.add(MUK);
		pokemons.add(SHELLDER);
		pokemons.add(CLOYSTER);
		pokemons.add(GASTLY);
		pokemons.add(HAUNTER);
		pokemons.add(GENGAR);
		pokemons.add(ONIX);
		pokemons.add(DROWZEE);
		pokemons.add(HYPNO);
		pokemons.add(KRABBY);
		pokemons.add(KINGLER);
		pokemons.add(VOLTORB);
		pokemons.add(ELECTRODE);
		pokemons.add(EXEGGCUTE);
		pokemons.add(EXEGGUTOR);
		pokemons.add(CUBONE);
		pokemons.add(MAROWAK);
		pokemons.add(HITMONLEE);
		pokemons.add(HITMONCHAN);
		pokemons.add(LICKITUNG);
		pokemons.add(KOFFING);
		pokemons.add(WEEZING);
		pokemons.add(RHYHORN);
		pokemons.add(RHYDON);
		pokemons.add(CHANSEY);
		pokemons.add(TANGELA);
		pokemons.add(KANGASKHAN);
		pokemons.add(HORSEA);
		pokemons.add(SEADRA);
		pokemons.add(GOLDEEN);
		pokemons.add(SEAKING);
		pokemons.add(STARYU);
		pokemons.add(STARMIE);
		pokemons.add(MRMIME);
		pokemons.add(SCYTHER);
		pokemons.add(JYNX);
		pokemons.add(ELECTABUZZ);
		pokemons.add(MAGMAR);
		pokemons.add(PINSIR);
		pokemons.add(TAUROS);
		pokemons.add(MAGIKARP);
		pokemons.add(GYARADOS);
		pokemons.add(LAPRAS);
		pokemons.add(DITTO);
		pokemons.add(EEVEE);
		pokemons.add(VAPOREON);
		pokemons.add(JOLTEON);
		pokemons.add(FLAREON);
		pokemons.add(PORYGON);
		pokemons.add(OMANYTE);
		pokemons.add(OMASTAR);
		pokemons.add(KABUTO);
		pokemons.add(KABUTOPS);
		pokemons.add(AERODACTYL);
		pokemons.add(SNORLAX);
		pokemons.add(ARTICUNO);
		pokemons.add(ZAPDOS);
		pokemons.add(MOLTRES);
		pokemons.add(DRATINI);
		pokemons.add(DRAGONAIR);
		pokemons.add(DRAGONITE);
		pokemons.add(MEWTWO);
		pokemons.add(MEW);
		pokemons.add(CHIKORITA);
		pokemons.add(BAYLEEF);
		pokemons.add(MEGANIUM);
		pokemons.add(CYNDAQUIL);
		pokemons.add(QUILAVA);
		pokemons.add(TYPHLOSION);
		pokemons.add(TOTODILE);
		pokemons.add(CROCONAW);
		pokemons.add(FERALIGATR);
		pokemons.add(SENTRET);
		pokemons.add(FURRET);
		pokemons.add(HOOTHOOT);
		pokemons.add(NOCTOWL);
		pokemons.add(LEDYBA);
		pokemons.add(LEDIAN);
		pokemons.add(SPINARAK);
		pokemons.add(ARIADOS);
		pokemons.add(CROBAT);
		pokemons.add(CHINCHOU);
		pokemons.add(LANTURN);
		pokemons.add(PICHU);
		pokemons.add(CLEFFA);
		pokemons.add(IGGLYBUFF);
		pokemons.add(TOGEPI);
		pokemons.add(TOGETIC);
		pokemons.add(NATU);
		pokemons.add(XATU);
		pokemons.add(MAREEP);
		pokemons.add(FLAAFFY);
		pokemons.add(AMPHAROS);
		pokemons.add(BELLOSSOM);
		pokemons.add(MARILL);
		pokemons.add(AZUMARILL);
		pokemons.add(SUDOWOODO);
		pokemons.add(POLITOED);
		pokemons.add(HOPPIP);
		pokemons.add(SKIPLOOM);
		pokemons.add(JUMPLUFF);
		pokemons.add(AIPOM);
		pokemons.add(SUNKERN);
		pokemons.add(SUNFLORA);
		pokemons.add(YANMA);
		pokemons.add(WOOPER);
		pokemons.add(QUAGSIRE);
		pokemons.add(ESPEON);
		pokemons.add(UMBREON);
		pokemons.add(MURKROW);
		pokemons.add(SLOWKING);
		pokemons.add(MISDREAVUS);
		pokemons.add(UNOWN);
		pokemons.add(WOBBUFFET);
		pokemons.add(GIRAFARIG);
		pokemons.add(PINECO);
		pokemons.add(FORRETRESS);
		pokemons.add(DUNSPARCE);
		pokemons.add(GLIGAR);
		pokemons.add(STEELIX);
		pokemons.add(SNUBBULL);
		pokemons.add(GRANBULL);
		pokemons.add(QWILFISH);
		pokemons.add(SCIZOR);
		pokemons.add(SHUCKLE);
		pokemons.add(HERACROSS);
		pokemons.add(SNEASEL);
		pokemons.add(TEDDIURSA);
		pokemons.add(URSARING);
		pokemons.add(SLUGMA);
		pokemons.add(MAGCARGO);
		pokemons.add(SWINUB);
		pokemons.add(PILOSWINE);
		pokemons.add(CORSOLA);
		pokemons.add(REMORAID);
		pokemons.add(OCTILLERY);
		pokemons.add(DELIBIRD);
		pokemons.add(MANTINE);
		pokemons.add(SKARMORY);
		pokemons.add(HOUNDOUR);
		pokemons.add(HOUNDOOM);
		pokemons.add(KINGDRA);
		pokemons.add(PHANPY);
		pokemons.add(DONPHAN);
		pokemons.add(PORYGON2);
		pokemons.add(STANTLER);
		pokemons.add(SMEARGLE);
		pokemons.add(TYROGUE);
		pokemons.add(HITMONTOP);
		pokemons.add(SMOOCHUM);
		pokemons.add(ELEKID);
		pokemons.add(MAGBY);
		pokemons.add(MILTANK);
		pokemons.add(BLISSEY);
		pokemons.add(RAIKOU);
		pokemons.add(ENTEI);
		pokemons.add(SUICUNE);
		pokemons.add(LARVITAR);
		pokemons.add(PUPITAR);
		pokemons.add(TYRANITAR);
		pokemons.add(LUGIA);
		pokemons.add(HOOH);
		pokemons.add(CELEBI);
		pokemons.add(TREECKO);
		pokemons.add(GROVYLE);
		pokemons.add(SCEPTILE);
		pokemons.add(TORCHIC);
		pokemons.add(COMBUSKEN);
		pokemons.add(BLAZIKEN);
		pokemons.add(MUDKIP);
		pokemons.add(MARSHTOMP);
		pokemons.add(SWAMPERT);
		pokemons.add(POOCHYENA);
		pokemons.add(MIGHTYENA);
		pokemons.add(ZIGZAGOON);
		pokemons.add(LINOONE);
		pokemons.add(WURMPLE);
		pokemons.add(SILCOON);
		pokemons.add(BEAUTIFLY);
		pokemons.add(CASCOON);
		pokemons.add(DUSTOX);
		pokemons.add(LOTAD);
		pokemons.add(LOMBRE);
		pokemons.add(LUDICOLO);
		pokemons.add(SEEDOT);
		pokemons.add(NUZLEAF);
		pokemons.add(SHIFTRY);
		pokemons.add(TAILLOW);
		pokemons.add(SWELLOW);
		pokemons.add(WINGULL);
		pokemons.add(PELIPPER);
		pokemons.add(RALTS);
		pokemons.add(KIRLIA);
		pokemons.add(GARDEVOIR);
		pokemons.add(SURSKIT);
		pokemons.add(MASQUERAIN);
		pokemons.add(SHROOMISH);
		pokemons.add(BRELOOM);
		pokemons.add(SLAKOTH);
		pokemons.add(VIGOROTH);
		pokemons.add(SLAKING);
		pokemons.add(NINCADA);
		pokemons.add(NINJASK);
		pokemons.add(SHEDINJA);
		pokemons.add(WHISMUR);
		pokemons.add(LOUDRED);
		pokemons.add(EXPLOUD);
		pokemons.add(MAKUHITA);
		pokemons.add(HARIYAMA);
		pokemons.add(AZURILL);
		pokemons.add(NOSEPASS);
		pokemons.add(SKITTY);
		pokemons.add(DELCATTY);
		pokemons.add(SABLEYE);
		pokemons.add(MAWILE);
		pokemons.add(ARON);
		pokemons.add(LAIRON);
		pokemons.add(AGGRON);
		pokemons.add(MEDITITE);
		pokemons.add(MEDICHAM);
		pokemons.add(ELECTRIKE);
		pokemons.add(MANECTRIC);
		pokemons.add(PLUSLE);
		pokemons.add(MINUN);
		pokemons.add(VOLBEAT);
		pokemons.add(ILLUMISE);
		pokemons.add(ROSELIA);
		pokemons.add(GULPIN);
		pokemons.add(SWALOT);
		pokemons.add(CARVANHA);
		pokemons.add(SHARPEDO);
		pokemons.add(WAILMER);
		pokemons.add(WAILORD);
		pokemons.add(NUMEL);
		pokemons.add(CAMERUPT);
		pokemons.add(TORKOAL);
		pokemons.add(SPOINK);
		pokemons.add(GRUMPIG);
		pokemons.add(SPINDA);
		pokemons.add(TRAPINCH);
		pokemons.add(VIBRAVA);
		pokemons.add(FLYGON);
		pokemons.add(CACNEA);
		pokemons.add(CACTURNE);
		pokemons.add(SWABLU);
		pokemons.add(ALTARIA);
		pokemons.add(ZANGOOSE);
		pokemons.add(SEVIPER);
		pokemons.add(LUNATONE);
		pokemons.add(SOLROCK);
		pokemons.add(BARBOACH);
		pokemons.add(WHISCASH);
		pokemons.add(CORPHISH);
		pokemons.add(CRAWDAUNT);
		pokemons.add(BALTOY);
		pokemons.add(CLAYDOL);
		pokemons.add(LILEEP);
		pokemons.add(CRADILY);
		pokemons.add(ANORITH);
		pokemons.add(ARMALDO);
		pokemons.add(FEEBAS);
		pokemons.add(MILOTIC);
		pokemons.add(CASTFORM);
		pokemons.add(KECLEON);
		pokemons.add(SHUPPET);
		pokemons.add(BANETTE);
		pokemons.add(DUSKULL);
		pokemons.add(DUSCLOPS);
		pokemons.add(TROPIUS);
		pokemons.add(CHIMECHO);
		pokemons.add(ABSOL);
		pokemons.add(WYNAUT);
		pokemons.add(SNORUNT);
		pokemons.add(GLALIE);
		pokemons.add(SPHEAL);
		pokemons.add(SEALEO);
		pokemons.add(WALREIN);
		pokemons.add(CLAMPERL);
		pokemons.add(HUNTAIL);
		pokemons.add(GOREBYSS);
		pokemons.add(RELICANTH);
		pokemons.add(LUVDISC);
		pokemons.add(BAGON);
		pokemons.add(SHELGON);
		pokemons.add(SALAMENCE);
		pokemons.add(BELDUM);
		pokemons.add(METANG);
		pokemons.add(METAGROSS);
		pokemons.add(REGIROCK);
		pokemons.add(REGICE);
		pokemons.add(REGISTEEL);
		pokemons.add(LATIAS);
		pokemons.add(LATIOS);
		pokemons.add(KYOGRE);
		pokemons.add(GROUDON);
		pokemons.add(RAYQUAZA);
		pokemons.add(JIRACHI);
		pokemons.add(DEOXYS);
		pokemons.add(TURTWIG);
		pokemons.add(GROTLE);
		pokemons.add(TORTERRA);
		pokemons.add(CHIMCHAR);
		pokemons.add(MONFERNO);
		pokemons.add(INFERNAPE);
		pokemons.add(PIPLUP);
		pokemons.add(PRINPLUP);
		pokemons.add(EMPOLEON);
		pokemons.add(STARLY);
		pokemons.add(STARAVIA);
		pokemons.add(STARAPTOR);
		pokemons.add(BIDOOF);
		pokemons.add(BIBAREL);
		pokemons.add(KRICKETOT);
		pokemons.add(KRICKETUNE);
		pokemons.add(SHINX);
		pokemons.add(LUXIO);
		pokemons.add(LUXRAY);
		pokemons.add(BUDEW);
		pokemons.add(ROSERADE);
		pokemons.add(CRANIDOS);
		pokemons.add(RAMPARDOS);
		pokemons.add(SHIELDON);
		pokemons.add(BASTIODON);
		pokemons.add(BURMY);
		pokemons.add(WORMADAM);
		pokemons.add(MOTHIM);
		pokemons.add(COMBEE);
		pokemons.add(VESPIQUEN);
		pokemons.add(PACHIRISU);
		pokemons.add(BUIZEL);
		pokemons.add(FLOATZEL);
		pokemons.add(CHERUBI);
		pokemons.add(CHERRIM);
		pokemons.add(SHELLOS);
		pokemons.add(GASTRODON);
		pokemons.add(AMBIPOM);
		pokemons.add(DRIFLOON);
		pokemons.add(DRIFBLIM);
		pokemons.add(BUNEARY);
		pokemons.add(LOPUNNY);
		pokemons.add(MISMAGIUS);
		pokemons.add(HONCHKROW);
		pokemons.add(GLAMEOW);
		pokemons.add(PURUGLY);
		pokemons.add(CHINGLING);
		pokemons.add(STUNKY);
		pokemons.add(SKUNTANK);
		pokemons.add(BRONZOR);
		pokemons.add(BRONZONG);
		pokemons.add(BONSLY);
		pokemons.add(MIMEJR);
		pokemons.add(HAPPINY);
		pokemons.add(CHATOT);
		pokemons.add(SPIRITOMB);
		pokemons.add(GIBLE);
		pokemons.add(GABITE);
		pokemons.add(GARCHOMP);
		pokemons.add(MUNCHLAX);
		pokemons.add(RIOLU);
		pokemons.add(LUCARIO);
		pokemons.add(HIPPOPOTAS);
		pokemons.add(HIPPOWDON);
		pokemons.add(SKORUPI);
		pokemons.add(DRAPION);
		pokemons.add(CROAGUNK);
		pokemons.add(TOXICROAK);
		pokemons.add(CARNIVINE);
		pokemons.add(FINNEON);
		pokemons.add(LUMINEON);
		pokemons.add(MANTYKE);
		pokemons.add(SNOVER);
		pokemons.add(ABOMASNOW);
		pokemons.add(WEAVILE);
		pokemons.add(MAGNEZONE);
		pokemons.add(LICKILICKY);
		pokemons.add(RHYPERIOR);
		pokemons.add(TANGROWTH);
		pokemons.add(ELECTIVIRE);
		pokemons.add(MAGMORTAR);
		pokemons.add(TOGEKISS);
		pokemons.add(YANMEGA);
		pokemons.add(LEAFEON);
		pokemons.add(GLACEON);
		pokemons.add(GLISCOR);
		pokemons.add(MAMOSWINE);
		pokemons.add(PORYGONZ);
		pokemons.add(GALLADE);
		pokemons.add(PROBOPASS);
		pokemons.add(DUSKNOIR);
		pokemons.add(FROSLASS);
		pokemons.add(ROTOM);
		pokemons.add(UXIE);
		pokemons.add(MESPRIT);
		pokemons.add(AZELF);
		pokemons.add(DIALGA);
		pokemons.add(PALKIA);
		pokemons.add(HEATRAN);
		pokemons.add(REGIGIGAS);
		pokemons.add(GIRATINA);
		pokemons.add(CRESSELIA);
		pokemons.add(PHIONE);
		pokemons.add(MANAPHY);
		pokemons.add(DARKRAI);
		pokemons.add(SHAYMIN);
		pokemons.add(ARCEUS);
		pokemons.add(VICTINI);
		pokemons.add(SNIVY);
		pokemons.add(SERVINE);
		pokemons.add(SERPERIOR);
		pokemons.add(TEPIG);
		pokemons.add(PIGNITE);
		pokemons.add(EMBOAR);
		pokemons.add(OSHAWOTT);
		pokemons.add(DEWOTT);
		pokemons.add(SAMUROTT);
		pokemons.add(PATRAT);
		pokemons.add(WATCHOG);
		pokemons.add(LILLIPUP);
		pokemons.add(HERDIER);
		pokemons.add(STOUTLAND);
		pokemons.add(PURRLOIN);
		pokemons.add(LIEPARD);
		pokemons.add(PANSAGE);
		pokemons.add(SIMISAGE);
		pokemons.add(PANSEAR);
		pokemons.add(SIMISEAR);
		pokemons.add(PANPOUR);
		pokemons.add(SIMIPOUR);
		pokemons.add(MUNNA);
		pokemons.add(MUSHARNA);
		pokemons.add(PIDOVE);
		pokemons.add(TRANQUILL);
		pokemons.add(UNFEZANT);
		pokemons.add(BLITZLE);
		pokemons.add(ZEBSTRIKA);
		pokemons.add(ROGGENROLA);
		pokemons.add(BOLDORE);
		pokemons.add(GIGALITH);
		pokemons.add(WOOBAT);
		pokemons.add(SWOOBAT);
		pokemons.add(DRILBUR);
		pokemons.add(EXCADRILL);
		pokemons.add(AUDINO);
		pokemons.add(TIMBURR);
		pokemons.add(GURDURR);
		pokemons.add(CONKELDURR);
		pokemons.add(TYMPOLE);
		pokemons.add(PALPITOAD);
		pokemons.add(SEISMITOAD);
		pokemons.add(THROH);
		pokemons.add(SAWK);
		pokemons.add(SEWADDLE);
		pokemons.add(SWADLOON);
		pokemons.add(LEAVANNY);
		pokemons.add(VENIPEDE);
		pokemons.add(WHIRLIPEDE);
		pokemons.add(SCOLIPEDE);
		pokemons.add(COTTONEE);
		pokemons.add(WHIMSICOTT);
		pokemons.add(PETILIL);
		pokemons.add(LILLIGANT);
		pokemons.add(BASCULIN);
		pokemons.add(SANDILE);
		pokemons.add(KROKOROK);
		pokemons.add(KROOKODILE);
		pokemons.add(DARUMAKA);
		pokemons.add(DARMANITAN);
		pokemons.add(MARACTUS);
		pokemons.add(DWEBBLE);
		pokemons.add(CRUSTLE);
		pokemons.add(SCRAGGY);
		pokemons.add(SCRAFTY);
		pokemons.add(SIGILYPH);
		pokemons.add(YAMASK);
		pokemons.add(COFAGRIGUS);
		pokemons.add(TIRTOUGA);
		pokemons.add(CARRACOSTA);
		pokemons.add(ARCHEN);
		pokemons.add(ARCHEOPS);
		pokemons.add(TRUBBISH);
		pokemons.add(GARBODOR);
		pokemons.add(ZORUA);
		pokemons.add(ZOROARK);
		pokemons.add(MINCCINO);
		pokemons.add(CINCCINO);
		pokemons.add(GOTHITA);
		pokemons.add(GOTHORITA);
		pokemons.add(GOTHITELLE);
		pokemons.add(SOLOSIS);
		pokemons.add(DUOSION);
		pokemons.add(REUNICLUS);
		pokemons.add(DUCKLETT);
		pokemons.add(SWANNA);
		pokemons.add(VANILLITE);
		pokemons.add(VANILLISH);
		pokemons.add(VANILLUXE);
		pokemons.add(DEERLING);
		pokemons.add(SAWSBUCK);
		pokemons.add(EMOLGA);
		pokemons.add(KARRABLAST);
		pokemons.add(ESCAVALIER);
		pokemons.add(FOONGUS);
		pokemons.add(AMOONGUSS);
		pokemons.add(FRILLISH);
		pokemons.add(JELLICENT);
		pokemons.add(ALOMOMOLA);
		pokemons.add(JOLTIK);
		pokemons.add(GALVANTULA);
		pokemons.add(FERROSEED);
		pokemons.add(FERROTHORN);
		pokemons.add(KLINK);
		pokemons.add(KLANG);
		pokemons.add(KLINKLANG);
		pokemons.add(TYNAMO);
		pokemons.add(EELEKTRIK);
		pokemons.add(EELEKTROSS);
		pokemons.add(ELGYEM);
		pokemons.add(BEHEEYEM);
		pokemons.add(LITWICK);
		pokemons.add(LAMPENT);
		pokemons.add(CHANDELURE);
		pokemons.add(AXEW);
		pokemons.add(FRAXURE);
		pokemons.add(HAXORUS);
		pokemons.add(CUBCHOO);
		pokemons.add(BEARTIC);
		pokemons.add(CRYOGONAL);
		pokemons.add(SHELMET);
		pokemons.add(ACCELGOR);
		pokemons.add(STUNFISK);
		pokemons.add(MIENFOO);
		pokemons.add(MIENSHAO);
		pokemons.add(DRUDDIGON);
		pokemons.add(GOLETT);
		pokemons.add(GOLURK);
		pokemons.add(PAWNIARD);
		pokemons.add(BISHARP);
		pokemons.add(BOUFFALANT);
		pokemons.add(RUFFLET);
		pokemons.add(BRAVIARY);
		pokemons.add(VULLABY);
		pokemons.add(MANDIBUZZ);
		pokemons.add(HEATMOR);
		pokemons.add(DURANT);
		pokemons.add(DEINO);
		pokemons.add(ZWEILOUS);
		pokemons.add(HYDREIGON);
		pokemons.add(LARVESTA);
		pokemons.add(VOLCARONA);
		pokemons.add(COBALION);
		pokemons.add(TERRAKION);
		pokemons.add(VIRIZION);
		pokemons.add(TORNADUS);
		pokemons.add(THUNDURUS);
		pokemons.add(RESHIRAM);
		pokemons.add(ZEKROM);
		pokemons.add(LANDORUS);
		pokemons.add(KYUREM);
		pokemons.add(KELDEO);
		pokemons.add(MELOETTA);
		pokemons.add(GENESECT);
		pokemons.add(CHESPIN);
		pokemons.add(QUILLADIN);
		pokemons.add(CHESNAUGHT);
		pokemons.add(FENNEKIN);
		pokemons.add(BRAIXEN);
		pokemons.add(DELPHOX);
		pokemons.add(FROAKIE);
		pokemons.add(FROGADIER);
		pokemons.add(GRENINJA);
		pokemons.add(BUNNELBY);
		pokemons.add(DIGGERSBY);
		pokemons.add(FLETCHLING);
		pokemons.add(FLETCHINDER);
		pokemons.add(TALONFLAME);
		pokemons.add(SCATTERBUG);
		pokemons.add(SPEWPA);
		pokemons.add(VIVILLON);
		pokemons.add(LITLEO);
		pokemons.add(PYROAR);
		pokemons.add(FLABEBE);
		pokemons.add(FLOETTE);
		pokemons.add(FLORGES);
		pokemons.add(SKIDDO);
		pokemons.add(GOGOAT);
		pokemons.add(PANCHAM);
		pokemons.add(PANGORO);
		pokemons.add(FURFROU);
		pokemons.add(ESPURR);
		pokemons.add(MEOWSTIC);
		pokemons.add(HONEDGE);
		pokemons.add(DOUBLADE);
		pokemons.add(AEGISLASH);
		pokemons.add(SPRITZEE);
		pokemons.add(AROMATISSE);
		pokemons.add(SWIRLIX);
		pokemons.add(SLURPUFF);
		pokemons.add(INKAY);
		pokemons.add(MALAMAR);
		pokemons.add(BINACLE);
		pokemons.add(BARBARACLE);
		pokemons.add(SKRELP);
		pokemons.add(DRAGALGE);
		pokemons.add(CLAUNCHER);
		pokemons.add(CLAWITZER);
		pokemons.add(HELIOPTILE);
		pokemons.add(HELIOLISK);
		pokemons.add(TYRUNT);
		pokemons.add(TYRANTRUM);
		pokemons.add(AMAURA);
		pokemons.add(AURORUS);
		pokemons.add(SYLVEON);
		pokemons.add(HAWLUCHA);
		pokemons.add(DEDENNE);
		pokemons.add(CARBINK);
		pokemons.add(GOOMY);
		pokemons.add(SLIGGOO);
		pokemons.add(GOODRA);
		pokemons.add(KLEFKI);
		pokemons.add(PHANTUMP);
		pokemons.add(TREVENANT);
		pokemons.add(PUMPKABOO);
		pokemons.add(GOURGEIST);
		pokemons.add(BERGMITE);
		pokemons.add(AVALUGG);
		pokemons.add(NOIBAT);
		pokemons.add(NOIVERN);
		pokemons.add(XERNEAS);
		pokemons.add(YVELTAL);
		pokemons.add(ZYGARDE);
		pokemons.add(DIANCIE);
		pokemons.add(HOOPA);
		pokemons.add(VOLCANION);
		pokemons.add(ROWLET);
		pokemons.add(DARTRIX);
		pokemons.add(DECIDUEYE);
		pokemons.add(LITTEN);
		pokemons.add(TORRACAT);
		pokemons.add(INCINEROAR);
		pokemons.add(POPPLIO);
		pokemons.add(BRIONNE);
		pokemons.add(PRIMARINA);
		pokemons.add(PIKIPEK);
		pokemons.add(TRUMBEAK);
		pokemons.add(TOUCANNON);
		pokemons.add(YUNGOOS);
		pokemons.add(GUMSHOOS);
		pokemons.add(GRUBBIN);
		pokemons.add(CHARJABUG);
		pokemons.add(VIKAVOLT);
		pokemons.add(CRABRAWLER);
		pokemons.add(CRABOMINABLE);
		pokemons.add(ORICORIO);
		pokemons.add(CUTIEFLY);
		pokemons.add(RIBOMBEE);
		pokemons.add(ROCKRUFF);
		pokemons.add(LYCANROC);
		pokemons.add(WISHIWASHI);
		pokemons.add(MAREANIE);
		pokemons.add(TOXAPEX);
		pokemons.add(MUDBRAY);
		pokemons.add(MUDSDALE);
		pokemons.add(DEWPIDER);
		pokemons.add(ARAQUANID);
		pokemons.add(FOMANTIS);
		pokemons.add(LURANTIS);
		pokemons.add(MORELULL);
		pokemons.add(SHIINOTIC);
		pokemons.add(SALANDIT);
		pokemons.add(SALAZZLE);
		pokemons.add(STUFFUL);
		pokemons.add(BEWEAR);
		pokemons.add(BOUNSWEET);
		pokemons.add(STEENEE);
		pokemons.add(TSAREENA);
		pokemons.add(COMFEY);
		pokemons.add(ORANGURU);
		pokemons.add(PASSIMIAN);
		pokemons.add(WIMPOD);
		pokemons.add(GOLISOPOD);
		pokemons.add(SANDYGAST);
		pokemons.add(PALOSSAND);
		pokemons.add(PYUKUMUKU);
		pokemons.add(TYPENULL);
		pokemons.add(SILVALLY);
		pokemons.add(MINIOR);
		pokemons.add(KOMALA);
		pokemons.add(TURTONATOR);
		pokemons.add(TOGEDEMARU);
		pokemons.add(MIMIKYU);
		pokemons.add(BRUXISH);
		pokemons.add(DRAMPA);
		pokemons.add(DHELMISE);
		pokemons.add(JANGMOO);
		pokemons.add(HAKAMOO);
		pokemons.add(KOMMOO);
		pokemons.add(TAPU_KOKO);
		pokemons.add(TAPU_LELE);
		pokemons.add(TAPU_BULU);
		pokemons.add(TAPU_FINI);
		pokemons.add(COSMOG);
		pokemons.add(COSMOEM);
		pokemons.add(SOLGALEO);
		pokemons.add(LUNALA);
		pokemons.add(NIHILEGO);
		pokemons.add(BUZZWOLE);
		pokemons.add(PHEROMOSA);
		pokemons.add(XURKITREE);
		pokemons.add(CELESTEELA);
		pokemons.add(KARTANA);
		pokemons.add(GUZZLORD);
		pokemons.add(NECROZMA);
		pokemons.add(MAGEARNA);
		pokemons.add(MARSHADOW);
		pokemons.add(POIPOLE);
		pokemons.add(NAGANADEL);
		pokemons.add(STAKATAKA);
		pokemons.add(BLACEPHALON);
		pokemons.add(ZERAORA);
		pokemons.add(MELTAN);
		pokemons.add(MELMETAL);
		pokemons.add(GROOKEY);
		pokemons.add(THWACKEY);
		pokemons.add(RILLABOOM);
		pokemons.add(SCORBUNNY);
		pokemons.add(RABOOT);
		pokemons.add(CINDERACE);
		pokemons.add(SOBBLE);
		pokemons.add(DRIZZILE);
		pokemons.add(INTELEON);
		pokemons.add(SKWOVET);
		pokemons.add(GREEDENT);
		pokemons.add(ROOKIDEE);
		pokemons.add(CORVISQUIRE);
		pokemons.add(CORVIKNIGHT);
		pokemons.add(BLIPBUG);
		pokemons.add(DOTTLER);
		pokemons.add(ORBEETLE);
		pokemons.add(NICKIT);
		pokemons.add(THIEVUL);
		pokemons.add(GOSSIFLEUR);
		pokemons.add(ELDEGOSS);
		pokemons.add(WOOLOO);
		pokemons.add(DUBWOOL);
		pokemons.add(CHEWTLE);
		pokemons.add(DREDNAW);
		pokemons.add(YAMPER);
		pokemons.add(BOLTUND);
		pokemons.add(ROLYCOLY);
		pokemons.add(CARKOL);
		pokemons.add(COALOSSAL);
		pokemons.add(APPLIN);
		pokemons.add(FLAPPLE);
		pokemons.add(APPLETUN);
		pokemons.add(SILICOBRA);
		pokemons.add(SANDACONDA);
		pokemons.add(CRAMORANT);
		pokemons.add(ARROKUDA);
		pokemons.add(BARRASKEWDA);
		pokemons.add(TOXEL);
		pokemons.add(TOXTRICITY);
		pokemons.add(SIZZLIPEDE);
		pokemons.add(CENTISKORCH);
		pokemons.add(CLOBBOPUS);
		pokemons.add(GRAPPLOCT);
		pokemons.add(SINISTEA);
		pokemons.add(POLTEAGEIST);
		pokemons.add(HATENNA);
		pokemons.add(HATTREM);
		pokemons.add(HATTERENE);
		pokemons.add(IMPIDIMP);
		pokemons.add(MORGREM);
		pokemons.add(GRIMMSNARL);
		pokemons.add(OBSTAGOON);
		pokemons.add(PERRSERKER);
		pokemons.add(CURSOLA);
		pokemons.add(SIRFETCHD);
		pokemons.add(MRRIME);
		pokemons.add(RUNERIGUS);
		pokemons.add(MILCERY);
		pokemons.add(ALCREMIE);
		pokemons.add(FALINKS);
		pokemons.add(PINCURCHIN);
		pokemons.add(SNOM);
		pokemons.add(FROSMOTH);
		pokemons.add(STONJOURNER);
		pokemons.add(EISCUE);
		pokemons.add(INDEEDEE);
		pokemons.add(MORPEKO);
		pokemons.add(DREEPY);
		pokemons.add(DRAKLOAK);
		pokemons.add(DRAGAPULT);

		legendaries.add(ARTICUNO);
		legendaries.add(ZAPDOS);
		legendaries.add(MOLTRES);
		legendaries.add(MEWTWO);
		legendaries.add(MEW);
		legendaries.add(RAIKOU);
		legendaries.add(ENTEI);
		legendaries.add(SUICUNE);
		legendaries.add(LUGIA);
		legendaries.add(HOOH);
		legendaries.add(CELEBI);
		legendaries.add(REGIROCK);
		legendaries.add(REGICE);
		legendaries.add(REGISTEEL);
		legendaries.add(LATIAS);
		legendaries.add(LATIOS);
		legendaries.add(KYOGRE);
		legendaries.add(GROUDON);
		legendaries.add(RAYQUAZA);
		legendaries.add(JIRACHI);
		legendaries.add(DEOXYS);
		legendaries.add(UXIE);
		legendaries.add(MESPRIT);
		legendaries.add(AZELF);
		legendaries.add(DIALGA);
		legendaries.add(PALKIA);
		legendaries.add(HEATRAN);
		legendaries.add(REGIGIGAS);
		legendaries.add(GIRATINA);
		legendaries.add(CRESSELIA);
		legendaries.add(PHIONE);
		legendaries.add(MANAPHY);
		legendaries.add(DARKRAI);
		legendaries.add(SHAYMIN);
		legendaries.add(ARCEUS);
		legendaries.add(COBALION);
		legendaries.add(TERRAKION);
		legendaries.add(VIRIZION);
		legendaries.add(TORNADUS);
		legendaries.add(THUNDURUS);
		legendaries.add(LANDORUS);
		legendaries.add(RESHIRAM);
		legendaries.add(ZEKROM);
		legendaries.add(KYUREM);
		legendaries.add(KELDEO);
		legendaries.add(MELOETTA);
		legendaries.add(GENESECT);
		legendaries.add(VICTINI);
		legendaries.add(XERNEAS);
		legendaries.add(YVELTAL);
		legendaries.add(ZYGARDE);
		legendaries.add(DIANCIE);
		legendaries.add(HOOPA);
		legendaries.add(VOLCANION);
		legendaries.add(TYPENULL);
		legendaries.add(SILVALLY);
		legendaries.add(TAPU_KOKO);
		legendaries.add(TAPU_LELE);
		legendaries.add(TAPU_BULU);
		legendaries.add(TAPU_FINI);
		legendaries.add(COSMOG);
		legendaries.add(COSMOEM);
		legendaries.add(SOLGALEO);
		legendaries.add(LUNALA);
		legendaries.add(NECROZMA);
		legendaries.add(MARSHADOW);
		legendaries.add(MAGEARNA);
		legendaries.add(ZERAORA);
		legendaries.add(MELTAN);
		legendaries.add(MELMETAL);
	}

	public static String getRandomName() {
		Random rand = new Random();
		int index = rand.nextInt(pokemons.size());
		return pokemons.get(index);
	}

	public static String getRandomNameWithoutLegendaries() {
		Random rand = new Random();
		List<String> list = pokemons;
		list.removeAll(legendaries);
		int index = rand.nextInt(list.size());
		return list.get(index);
	}
}
