package com.pippohsios.betterpixelmon.storage;

import java.util.ArrayList;
import java.util.List;

public class Tier1DropStorage {
	public static final String POKE_BALL = "pixelmon:poke_ball";
	public static final String GREAT_BALL = "pixelmon:great_ball";
	public static final String ULTRA_BALL = "pixelmon:ultra_ball";
	public static final String LEVEL_BALL = "pixelmon:level_ball";
	public static final String MOON_BALL = "pixelmon:moon_ball";
	public static final String FRIEND_BALL = "pixelmon:friend_ball";
	public static final String LOVE_BALL = "pixelmon:love_ball";
	public static final String HEAVY_BALL = "pixelmon:heavy_ball";
	public static final String FAST_BALL = "pixelmon:fast_ball";
	public static final String REPEAT_BALL = "pixelmon:repeat_ball";
	public static final String TIMER_BALL = "pixelmon:timer_ball";
	public static final String NEST_BALL = "pixelmon:nest_ball";
	public static final String NET_BALL = "pixelmon:net_ball";
	public static final String DIVE_BALL = "pixelmon:dive_ball";
	public static final String LUXURY_BALL = "pixelmon:luxury_ball";
	public static final String HEAL_BALL = "pixelmon:heal_ball";
	public static final String DUSK_BALL = "pixelmon:dusk_ball";
	public static final String QUICK_BALL = "pixelmon:quick_ball";
	public static final String LURE_BALL = "pixelmon:lure_ball";
	public static final String SPORT_BALL = "pixelmon:sport_ball";
	public static final String PREMIER_BALL = "pixelmon:premier_ball";
	public static final String SAFARI_BALL = "pixelmon:safari_ball";
	public static final String RARE_CANDY = "pixelmon:rare_candy";
	public static final String POTION = "pixelmon:potion";
	public static final String SUPER_POTION = "pixelmon:super_potion";
	public static final String HYPER_POTION = "pixelmon:hyper_potion";
	public static final String MAX_POTION = "pixelmon:max_potion";
	public static final String FULL_RESTORE = "pixelmon:full_restore";
	public static final String FRESH_WATER = "pixelmon:fresh_water";
	public static final String SODA_POP = "pixelmon:soda_pop";
	public static final String LEMONADE = "pixelmon:lemonade";
	public static final String MOOMOO_MILK = "pixelmon:moomoo_milk";
	public static final String REVIVE = "pixelmon:revive";
	public static final String MAX_REVIVE = "pixelmon:max_revive";
	public static final String ETHER = "pixelmon:ether";
	public static final String MAX_ETHER = "pixelmon:max_ether";
	public static final String ELIXIR = "pixelmon:elixir";
	public static final String MAX_ELIXIR = "pixelmon:max_elixir";
	public static final String ANTIDOTE = "pixelmon:antidote";
	public static final String PARALYZE_HEAL = "pixelmon:paralyze_heal";
	public static final String AWAKENING = "pixelmon:awakening";
	public static final String BURN_HEAL = "pixelmon:burn_heal";
	public static final String ICE_HEAL = "pixelmon:ice_heal";
	public static final String FULL_HEAL = "pixelmon:full_heal";
	public static final String HP_UP = "pixelmon:hp_up";
	public static final String PROTEIN = "pixelmon:protein";
	public static final String IRON = "pixelmon:iron";
	public static final String CALCIUM = "pixelmon:calcium";
	public static final String ZINC = "pixelmon:zinc";
	public static final String CARBOS = "pixelmon:carbos";
	public static final String HEAL_POWDER = "pixelmon:heal_powder";
	public static final String ENERGY_POWDER = "pixelmon:energy_powder";
	public static final String ENERGY_ROOT = "pixelmon:energy_root";
	public static final String REVIVAL_HERB = "pixelmon:revival_herb";
	public static final String X_ATTACK = "pixelmon:x_attack";
	public static final String X_DEFENCE = "pixelmon:x_defence";
	public static final String X_SPECIAL_ATTACK = "pixelmon:x_special_attack";
	public static final String X_SPECIAL_DEFENCE = "pixelmon:x_special_defence";
	public static final String X_SPEED = "pixelmon:x_speed";
	public static final String X_ACCURACY = "pixelmon:x_accuracy";
	public static final String DIRE_HIT = "pixelmon:dire_hit";
	public static final String POMEG_BERRY = "pixelmon:pomeg_berry";
	public static final String KELPSY_BERRY = "pixelmon:kelpsy_berry";
	public static final String QUALOT_BERRY = "pixelmon:qualot_berry";
	public static final String HONDEW_BERRY = "pixelmon:hondew_berry";
	public static final String GREPA_BERRY = "pixelmon:grepa_berry";
	public static final String TAMATO_BERRY = "pixelmon:tamato_berry";
	public static final String ORAN_BERRY = "pixelmon:oran_berry";
	public static final String RAWST_BERRY = "pixelmon:rawst_berry";
	public static final String LEPPA_BERRY = "pixelmon:leppa_berry";
	public static final String CHERI_BERRY = "pixelmon:cheri_berry";
	public static final String CHESTO_BERRY = "pixelmon:chesto_berry";
	public static final String PECHA_BERRY = "pixelmon:pecha_berry";
	public static final String ASPEAR_BERRY = "pixelmon:aspear_berry";
	public static final String PERSIM_BERRY = "pixelmon:persim_berry";
	public static final String BERRY_JUICE = "pixelmon:berry_juice";
	public static final String PUMKIN_BERRY = "pixelmon:pumkin_berry";
	public static final String DRASH_BERRY = "pixelmon:drash_berry";
	public static final String EGGANT_BERRY = "pixelmon:eggant_berry";
	public static final String YAGO_BERRY = "pixelmon:yago_berry";
	public static final String TOUGA_BERRY = "pixelmon:touga_berry";
	public static final String APICOT_BERRY = "pixelmon:apicot_berry";
	public static final String GANLON_BERRY = "pixelmon:ganlon_berry";
	public static final String LANSAT_BERRY = "pixelmon:lansat_berry";
	public static final String STARF_BERRY = "pixelmon:starf_berry";
	public static final String AGUAV_BERRY = "pixelmon:aguav_berry";
	public static final String FIGY_BERRY = "pixelmon:figy_berry";
	public static final String IAPAPA_BERRY = "pixelmon:iapapa_berry";
	public static final String MAGO_BERRY = "pixelmon:mago_berry";
	public static final String WIKI_BERRY = "pixelmon:wiki_berry";
	public static final String JABOCA_BERRY = "pixelmon:jaboca_berry";
	public static final String ROWAP_BERRY = "pixelmon:rowap_berry";
	public static final String ENIGMA_BERRY = "pixelmon:enigma_berry";
	public static final String MICLE_BERRY = "pixelmon:micle_berry";
	public static final String LUCKY_PUNCH = "pixelmon:lucky_punch";
	public static final String METAL_POWDER = "pixelmon:metal_powder";
	public static final String QUICK_POWDER = "pixelmon:quick_powder";
	public static final String LEEK = "pixelmon:leek";
	public static final String EVER_STONE = "pixelmon:ever_stone";
	public static final String ABSORB_BULB = "pixelmon:absorb_bulb";
	public static final String CELL_BATTERY = "pixelmon:cell_battery";
	public static final String SHED_SHELL = "pixelmon:shed_shell";
	public static final String STICKY_BARB = "pixelmon:sticky_barb";
	public static final String BIG_ROOT = "pixelmon:big_root";
	public static final String BINDING_BAND = "pixelmon:binding_band";
	public static final String GRIP_CLAW = "pixelmon:grip_claw";
	public static final String FLOAT_STONE = "pixelmon:float_stone";
	public static final String RING_TARGET = "pixelmon:ring_target";
	public static final String PURE_INCENSE = "pixelmon:pure_incense";
	public static final String LUMINOUS_MOSS = "pixelmon:luminous_moss";
	public static final String SNOWBALL = "pixelmon:snowball";
	public static final String POKEMAIL_AIR = "pixelmon:pokemail_air";
	public static final String POKEMAIL_BLOOM = "pixelmon:pokemail_bloom";
	public static final String POKEMAIL_BRICK = "pixelmon:pokemail_brick";
	public static final String POKEMAIL_BRIDGED = "pixelmon:pokemail_bridged";
	public static final String POKEMAIL_BRIDGEM = "pixelmon:pokemail_bridgem";
	public static final String POKEMAIL_BRIDGES = "pixelmon:pokemail_bridges";
	public static final String POKEMAIL_BRIDGEV = "pixelmon:pokemail_bridgev";
	public static final String POKEMAIL_BUBBLE = "pixelmon:pokemail_bubble";
	public static final String POKEMAIL_DREAM = "pixelmon:pokemail_dream";
	public static final String POKEMAIL_FAB = "pixelmon:pokemail_fab";
	public static final String POKEMAIL_FAVORED = "pixelmon:pokemail_favored";
	public static final String POKEMAIL_FLAME = "pixelmon:pokemail_flame";
	public static final String POKEMAIL_GLITTER = "pixelmon:pokemail_glitter";
	public static final String POKEMAIL_GRASS = "pixelmon:pokemail_grass";
	public static final String POKEMAIL_GREET = "pixelmon:pokemail_greet";
	public static final String POKEMAIL_HEART = "pixelmon:pokemail_heart";
	public static final String POKEMAIL_INQUIRY = "pixelmon:pokemail_inquiry";
	public static final String POKEMAIL_LIKE = "pixelmon:pokemail_like";
	public static final String POKEMAIL_MECH = "pixelmon:pokemail_mech";
	public static final String POKEMAIL_MOSAIC = "pixelmon:pokemail_mosaic";
	public static final String POKEMAIL_ORANGE = "pixelmon:pokemail_orange";
	public static final String POKEMAIL_REPLY = "pixelmon:pokemail_reply";
	public static final String POKEMAIL_RETRO = "pixelmon:pokemail_retro";
	public static final String POKEMAIL_RSVP = "pixelmon:pokemail_rsvp";
	public static final String POKEMAIL_SNOW = "pixelmon:pokemail_snow";
	public static final String POKEMAIL_SPACE = "pixelmon:pokemail_space";
	public static final String POKEMAIL_STEEL = "pixelmon:pokemail_steel";
	public static final String POKEMAIL_THANKS = "pixelmon:pokemail_thanks";
	public static final String POKEMAIL_WAVE = "pixelmon:pokemail_wave";
	public static final String POKEMAIL_WOOD = "pixelmon:pokemail_wood";
	public static final String TM19 = "pixelmon:tm19";
	public static final String TM48 = "pixelmon:tm48";
	public static final String TM49 = "pixelmon:tm49";
	public static final String TM51 = "pixelmon:tm51";
	public static final String TM59 = "pixelmon:tm59";
	public static final String TM60 = "pixelmon:tm60";
	public static final String TM63 = "pixelmon:tm63";
	public static final String TM70 = "pixelmon:tm70";
	public static final String TM76 = "pixelmon:tm76";
	public static final String TM105 = "pixelmon:tm105";
	public static final String TM110 = "pixelmon:tm110";
	public static final String TM111 = "pixelmon:tm111";
	public static final String TM112 = "pixelmon:tm112";
	public static final String TM120 = "pixelmon:tm120";
	public static final String TM124 = "pixelmon:tm124";
	public static final String TM131 = "pixelmon:tm131";
	public static final String TM132 = "pixelmon:tm132";
	public static final String TM138 = "pixelmon:tm138";
	public static final String TM141 = "pixelmon:tm141";
	public static final String TM146 = "pixelmon:tm146";
	public static final String TM150 = "pixelmon:tm150";
	public static final String TM160 = "pixelmon:tm160";
	public static final String TM163 = "pixelmon:tm163";
	public static final String TM166 = "pixelmon:tm166";
	public static final String TM170 = "pixelmon:tm170";
	public static final String HM5 = "pixelmon:hm5";
	public static final String HOURGLASS_SILVER = "pixelmon:hourglass_silver";
	public static final String FILM = "pixelmon:film";

	public static List<String> drops = new ArrayList<String>();

	public static void init() {
		drops.add(POKE_BALL);
		drops.add(GREAT_BALL);
		drops.add(ULTRA_BALL);
		drops.add(LEVEL_BALL);
		drops.add(MOON_BALL);
		drops.add(FRIEND_BALL);
		drops.add(LOVE_BALL);
		drops.add(HEAVY_BALL);
		drops.add(FAST_BALL);
		drops.add(REPEAT_BALL);
		drops.add(TIMER_BALL);
		drops.add(NEST_BALL);
		drops.add(NET_BALL);
		drops.add(DIVE_BALL);
		drops.add(LUXURY_BALL);
		drops.add(HEAL_BALL);
		drops.add(DUSK_BALL);
		drops.add(QUICK_BALL);
		drops.add(LURE_BALL);
		drops.add(SPORT_BALL);
		drops.add(PREMIER_BALL);
		drops.add(SAFARI_BALL);
		drops.add(RARE_CANDY);
		drops.add(POTION);
		drops.add(SUPER_POTION);
		drops.add(HYPER_POTION);
		drops.add(MAX_POTION);
		drops.add(FULL_RESTORE);
		drops.add(FRESH_WATER);
		drops.add(SODA_POP);
		drops.add(LEMONADE);
		drops.add(MOOMOO_MILK);
		drops.add(REVIVE);
		drops.add(MAX_REVIVE);
		drops.add(ETHER);
		drops.add(MAX_ETHER);
		drops.add(ELIXIR);
		drops.add(MAX_ELIXIR);
		drops.add(ANTIDOTE);
		drops.add(PARALYZE_HEAL);
		drops.add(AWAKENING);
		drops.add(BURN_HEAL);
		drops.add(ICE_HEAL);
		drops.add(FULL_HEAL);
		drops.add(HP_UP);
		drops.add(PROTEIN);
		drops.add(IRON);
		drops.add(CALCIUM);
		drops.add(ZINC);
		drops.add(CARBOS);
		drops.add(HEAL_POWDER);
		drops.add(ENERGY_POWDER);
		drops.add(ENERGY_ROOT);
		drops.add(REVIVAL_HERB);
		drops.add(X_ATTACK);
		drops.add(X_DEFENCE);
		drops.add(X_SPECIAL_ATTACK);
		drops.add(X_SPECIAL_DEFENCE);
		drops.add(X_SPEED);
		drops.add(X_ACCURACY);
		drops.add(DIRE_HIT);
		drops.add(POMEG_BERRY);
		drops.add(KELPSY_BERRY);
		drops.add(QUALOT_BERRY);
		drops.add(HONDEW_BERRY);
		drops.add(GREPA_BERRY);
		drops.add(TAMATO_BERRY);
		drops.add(ORAN_BERRY);
		drops.add(RAWST_BERRY);
		drops.add(LEPPA_BERRY);
		drops.add(CHERI_BERRY);
		drops.add(CHESTO_BERRY);
		drops.add(PECHA_BERRY);
		drops.add(ASPEAR_BERRY);
		drops.add(PERSIM_BERRY);
		drops.add(BERRY_JUICE);
		drops.add(PUMKIN_BERRY);
		drops.add(DRASH_BERRY);
		drops.add(EGGANT_BERRY);
		drops.add(YAGO_BERRY);
		drops.add(TOUGA_BERRY);
		drops.add(APICOT_BERRY);
		drops.add(GANLON_BERRY);
		drops.add(LANSAT_BERRY);
		drops.add(STARF_BERRY);
		drops.add(AGUAV_BERRY);
		drops.add(FIGY_BERRY);
		drops.add(IAPAPA_BERRY);
		drops.add(MAGO_BERRY);
		drops.add(WIKI_BERRY);
		drops.add(JABOCA_BERRY);
		drops.add(ROWAP_BERRY);
		drops.add(ENIGMA_BERRY);
		drops.add(MICLE_BERRY);
		drops.add(LUCKY_PUNCH);
		drops.add(METAL_POWDER);
		drops.add(QUICK_POWDER);
		drops.add(LEEK);
		drops.add(EVER_STONE);
		drops.add(ABSORB_BULB);
		drops.add(CELL_BATTERY);
		drops.add(SHED_SHELL);
		drops.add(STICKY_BARB);
		drops.add(BIG_ROOT);
		drops.add(BINDING_BAND);
		drops.add(GRIP_CLAW);
		drops.add(FLOAT_STONE);
		drops.add(RING_TARGET);
		drops.add(PURE_INCENSE);
		drops.add(LUMINOUS_MOSS);
		drops.add(SNOWBALL);
		drops.add(POKEMAIL_AIR);
		drops.add(POKEMAIL_BLOOM);
		drops.add(POKEMAIL_BRICK);
		drops.add(POKEMAIL_BRIDGED);
		drops.add(POKEMAIL_BRIDGEM);
		drops.add(POKEMAIL_BRIDGES);
		drops.add(POKEMAIL_BRIDGEV);
		drops.add(POKEMAIL_BUBBLE);
		drops.add(POKEMAIL_DREAM);
		drops.add(POKEMAIL_FAB);
		drops.add(POKEMAIL_FAVORED);
		drops.add(POKEMAIL_FLAME);
		drops.add(POKEMAIL_GLITTER);
		drops.add(POKEMAIL_GRASS);
		drops.add(POKEMAIL_GREET);
		drops.add(POKEMAIL_HEART);
		drops.add(POKEMAIL_INQUIRY);
		drops.add(POKEMAIL_LIKE);
		drops.add(POKEMAIL_MECH);
		drops.add(POKEMAIL_MOSAIC);
		drops.add(POKEMAIL_ORANGE);
		drops.add(POKEMAIL_REPLY);
		drops.add(POKEMAIL_RETRO);
		drops.add(POKEMAIL_RSVP);
		drops.add(POKEMAIL_SNOW);
		drops.add(POKEMAIL_SPACE);
		drops.add(POKEMAIL_STEEL);
		drops.add(POKEMAIL_THANKS);
		drops.add(POKEMAIL_WAVE);
		drops.add(POKEMAIL_WOOD);
		drops.add(TM19);
		drops.add(TM48);
		drops.add(TM49);
		drops.add(TM51);
		drops.add(TM59);
		drops.add(TM60);
		drops.add(TM63);
		drops.add(TM70);
		drops.add(TM76);
		drops.add(TM105);
		drops.add(TM110);
		drops.add(TM111);
		drops.add(TM112);
		drops.add(TM120);
		drops.add(TM124);
		drops.add(TM131);
		drops.add(TM132);
		drops.add(TM138);
		drops.add(TM141);
		drops.add(TM146);
		drops.add(TM150);
		drops.add(TM160);
		drops.add(TM163);
		drops.add(TM166);
		drops.add(TM170);
		drops.add(HM5);
		drops.add(HOURGLASS_SILVER);
		drops.add(FILM);
	}
}
