package com.pippohsios.betterpixelmon.storage;

import java.util.ArrayList;
import java.util.List;

public class Tier3DropStorage {
	public static final String PP_MAX = "pixelmon:pp_max";
	public static final String MASTER_BALL = "pixelmon:master_ball";
	public static final String LUCKY_EGG = "pixelmon:lucky_egg";
	public static final String EXP_ALL = "pixelmon:exp_all";
	public static final String CHOICE_BAND = "pixelmon:choice_band";
	public static final String CHOICE_SCARF = "pixelmon:choice_scarf";
	public static final String CHOICE_SPECS = "pixelmon:choice_specs";
	public static final String POWER_WEIGHT = "pixelmon:power_weight";
	public static final String POWER_BRACER = "pixelmon:power_bracer";
	public static final String POWER_BELT = "pixelmon:power_belt";
	public static final String POWER_LENS = "pixelmon:power_lens";
	public static final String POWER_BAND = "pixelmon:power_band";
	public static final String POWER_ANKLET = "pixelmon:power_anklet";
	public static final String MUSCLE_BAND = "pixelmon:muscle_band";
	public static final String LEFTOVERS = "pixelmon:leftovers";
	public static final String LIFE_ORB = "pixelmon:life_orb";
	public static final String FOCUS_SASH = "pixelmon:focus_sash";
	public static final String ROCKY_HELMET = "pixelmon:rocky_helmet";
	public static final String EVIOLITE = "pixelmon:eviolite";
	public static final String EXPERT_BELT = "pixelmon:expert_belt";
	public static final String WISE_GLASSES = "pixelmon:wise_glasses";
	public static final String DESTINY_KNOT = "pixelmon:destiny_knot";
	public static final String ASSAULT_VEST = "pixelmon:assault_vest";
	public static final String WEAKNESS_POLICY = "pixelmon:weakness_policy";
	public static final String ABILITY_CAPSULE = "pixelmon:ability_capsule";
	public static final String SOUL_DEW = "pixelmon:soul_dew";
	public static final String SILVER_BOTTLE_CAP = "pixelmon:silver_bottle_cap";
	public static final String TM2 = "pixelmon:tm2";
	public static final String TM3 = "pixelmon:tm3";
	public static final String TM4 = "pixelmon:tm4";
	public static final String TM5 = "pixelmon:tm5";
	public static final String TM6 = "pixelmon:tm6";
	public static final String TM7 = "pixelmon:tm7";
	public static final String TM8 = "pixelmon:tm8";
	public static final String TM10 = "pixelmon:tm10";
	public static final String TM11 = "pixelmon:tm11";
	public static final String TM12 = "pixelmon:tm12";
	public static final String TM13 = "pixelmon:tm13";
	public static final String TM14 = "pixelmon:tm14";
	public static final String TM15 = "pixelmon:tm15";
	public static final String TM16 = "pixelmon:tm16";
	public static final String TM17 = "pixelmon:tm17";
	public static final String TM18 = "pixelmon:tm18";
	public static final String TM22 = "pixelmon:tm22";
	public static final String TM24 = "pixelmon:tm24";
	public static final String TM25 = "pixelmon:tm25";
	public static final String TM26 = "pixelmon:tm26";
	public static final String TM27 = "pixelmon:tm27";
	public static final String TM29 = "pixelmon:tm29";
	public static final String TM30 = "pixelmon:tm30";
	public static final String TM31 = "pixelmon:tm31";
	public static final String TM33 = "pixelmon:tm33";
	public static final String TM34 = "pixelmon:tm34";
	public static final String TM35 = "pixelmon:tm35";
	public static final String TM36 = "pixelmon:tm36";
	public static final String TM37 = "pixelmon:tm37";
	public static final String TM38 = "pixelmon:tm38";
	public static final String TM42 = "pixelmon:tm42";
	public static final String TM43 = "pixelmon:tm43";
	public static final String TM44 = "pixelmon:tm44";
	public static final String TM45 = "pixelmon:tm45";
	public static final String TM50 = "pixelmon:tm50";
	public static final String TM52 = "pixelmon:tm52";
	public static final String TM53 = "pixelmon:tm53";
	public static final String TM54 = "pixelmon:tm54";
	public static final String TM55 = "pixelmon:tm55";
	public static final String TM61 = "pixelmon:tm61";
	public static final String TM62 = "pixelmon:tm62";
	public static final String TM64 = "pixelmon:tm64";
	public static final String TM65 = "pixelmon:tm65";
	public static final String TM66 = "pixelmon:tm66";
	public static final String TM68 = "pixelmon:tm68";
	public static final String TM69 = "pixelmon:tm69";
	public static final String TM71 = "pixelmon:tm71";
	public static final String TM72 = "pixelmon:tm72";
	public static final String TM73 = "pixelmon:tm73";
	public static final String TM74 = "pixelmon:tm74";
	public static final String TM75 = "pixelmon:tm75";
	public static final String TM80 = "pixelmon:tm80";
	public static final String TM81 = "pixelmon:tm81";
	public static final String TM82 = "pixelmon:tm82";
	public static final String TM84 = "pixelmon:tm84";
	public static final String TM86 = "pixelmon:tm86";
	public static final String TM87 = "pixelmon:tm87";
	public static final String TM89 = "pixelmon:tm89";
	public static final String TM90 = "pixelmon:tm90";
	public static final String TM91 = "pixelmon:tm91";
	public static final String TM92 = "pixelmon:tm92";
	public static final String TM93 = "pixelmon:tm93";
	public static final String TM98 = "pixelmon:tm98";
	public static final String TM99 = "pixelmon:tm99";
	public static final String TM100 = "pixelmon:tm100";
	public static final String TM101 = "pixelmon:tm101";
	public static final String TM103 = "pixelmon:tm103";
	public static final String TM108 = "pixelmon:tm108";
	public static final String TM113 = "pixelmon:tm113";
	public static final String TM123 = "pixelmon:tm123";
	public static final String TM126 = "pixelmon:tm126";
	public static final String TM128 = "pixelmon:tm128";
	public static final String TM130 = "pixelmon:tm130";
	public static final String TM133 = "pixelmon:tm133";
	public static final String TM134 = "pixelmon:tm134";
	public static final String TM136 = "pixelmon:tm136";
	public static final String TM139 = "pixelmon:tm139";
	public static final String TM140 = "pixelmon:tm140";
	public static final String TM142 = "pixelmon:tm142";
	public static final String TM143 = "pixelmon:tm143";
	public static final String TM145 = "pixelmon:tm145";
	public static final String TM148 = "pixelmon:tm148";
	public static final String TM155 = "pixelmon:tm155";
	public static final String TM157 = "pixelmon:tm157";
	public static final String TM158 = "pixelmon:tm158";
	public static final String TM161 = "pixelmon:tm161";
	public static final String TM162 = "pixelmon:tm162";
	public static final String TM164 = "pixelmon:tm164";
	public static final String TM169 = "pixelmon:tm169";
	public static final String HM2 = "pixelmon:hm2";
	public static final String HM3 = "pixelmon:hm3";
	public static final String HM7 = "pixelmon:hm7";
	public static final String HEAVY_DUTY_BOOTS = "pixelmon:heavy_duty_boots";
	public static final String THROAT_SPRAY = "pixelmon:throat_spray";
	public static final String ROOM_SERVICE = "pixelmon:room_service";

	public static List<String> drops = new ArrayList<String>();

	public static void init() {
		drops.add(PP_MAX);
		drops.add(MASTER_BALL);
		drops.add(LUCKY_EGG);
		drops.add(EXP_ALL);
		drops.add(CHOICE_BAND);
		drops.add(CHOICE_SCARF);
		drops.add(CHOICE_SPECS);
		drops.add(POWER_WEIGHT);
		drops.add(POWER_BRACER);
		drops.add(POWER_BELT);
		drops.add(POWER_LENS);
		drops.add(POWER_BAND);
		drops.add(POWER_ANKLET);
		drops.add(MUSCLE_BAND);
		drops.add(LEFTOVERS);
		drops.add(LIFE_ORB);
		drops.add(FOCUS_SASH);
		drops.add(ROCKY_HELMET);
		drops.add(EVIOLITE);
		drops.add(EXPERT_BELT);
		drops.add(WISE_GLASSES);
		drops.add(DESTINY_KNOT);
		drops.add(ASSAULT_VEST);
		drops.add(WEAKNESS_POLICY);
		drops.add(ABILITY_CAPSULE);
		drops.add(SOUL_DEW);
		drops.add(SILVER_BOTTLE_CAP);
		drops.add(TM2);
		drops.add(TM3);
		drops.add(TM4);
		drops.add(TM5);
		drops.add(TM6);
		drops.add(TM7);
		drops.add(TM8);
		drops.add(TM10);
		drops.add(TM11);
		drops.add(TM12);
		drops.add(TM13);
		drops.add(TM14);
		drops.add(TM15);
		drops.add(TM16);
		drops.add(TM17);
		drops.add(TM18);
		drops.add(TM22);
		drops.add(TM24);
		drops.add(TM25);
		drops.add(TM26);
		drops.add(TM27);
		drops.add(TM29);
		drops.add(TM30);
		drops.add(TM31);
		drops.add(TM33);
		drops.add(TM34);
		drops.add(TM35);
		drops.add(TM36);
		drops.add(TM37);
		drops.add(TM38);
		drops.add(TM42);
		drops.add(TM43);
		drops.add(TM44);
		drops.add(TM45);
		drops.add(TM50);
		drops.add(TM52);
		drops.add(TM53);
		drops.add(TM54);
		drops.add(TM55);
		drops.add(TM61);
		drops.add(TM62);
		drops.add(TM64);
		drops.add(TM65);
		drops.add(TM66);
		drops.add(TM68);
		drops.add(TM69);
		drops.add(TM71);
		drops.add(TM72);
		drops.add(TM73);
		drops.add(TM74);
		drops.add(TM75);
		drops.add(TM80);
		drops.add(TM81);
		drops.add(TM82);
		drops.add(TM84);
		drops.add(TM86);
		drops.add(TM87);
		drops.add(TM89);
		drops.add(TM90);
		drops.add(TM91);
		drops.add(TM92);
		drops.add(TM93);
		drops.add(TM98);
		drops.add(TM99);
		drops.add(TM100);
		drops.add(TM101);
		drops.add(TM103);
		drops.add(TM108);
		drops.add(TM113);
		drops.add(TM123);
		drops.add(TM126);
		drops.add(TM128);
		drops.add(TM130);
		drops.add(TM133);
		drops.add(TM134);
		drops.add(TM136);
		drops.add(TM139);
		drops.add(TM140);
		drops.add(TM142);
		drops.add(TM143);
		drops.add(TM145);
		drops.add(TM148);
		drops.add(TM155);
		drops.add(TM157);
		drops.add(TM158);
		drops.add(TM161);
		drops.add(TM162);
		drops.add(TM164);
		drops.add(TM169);
		drops.add(HM2);
		drops.add(HM3);
		drops.add(HM7);
		drops.add(HEAVY_DUTY_BOOTS);
		drops.add(THROAT_SPRAY);
		drops.add(ROOM_SERVICE);
	}
}
