package com.pippohsios.betterpixelmon.storage;

import java.util.ArrayList;
import java.util.List;

public class Tier2DropStorage {
	public static final String PP_UP = "pixelmon:pp_up";
	public static final String CHERISH_BALL = "pixelmon:cherish_ball";
	public static final String LUM_BERRY = "pixelmon:lum_berry";
	public static final String SITRUS_BERRY = "pixelmon:sitrus_berry";
	public static final String LIECHI_BERRY = "pixelmon:liechi_berry";
	public static final String SALAC_BERRY = "pixelmon:salac_berry";
	public static final String PETAYA_BERRY = "pixelmon:petaya_berry";
	public static final String CUSTAP_BERRY = "pixelmon:custap_berry";
	public static final String OCCA_BERRY = "pixelmon:occa_berry";
	public static final String PASSHO_BERRY = "pixelmon:passho_berry";
	public static final String WACAN_BERRY = "pixelmon:wacan_berry";
	public static final String RINDO_BERRY = "pixelmon:rindo_berry";
	public static final String YACHE_BERRY = "pixelmon:yache_berry";
	public static final String CHOPLE_BERRY = "pixelmon:chople_berry";
	public static final String KEBIA_BERRY = "pixelmon:kebia_berry";
	public static final String SHUCA_BERRY = "pixelmon:shuca_berry";
	public static final String COBA_BERRY = "pixelmon:coba_berry";
	public static final String PAYAPA_BERRY = "pixelmon:payapa_berry";
	public static final String TANGA_BERRY = "pixelmon:tanga_berry";
	public static final String CHARTI_BERRY = "pixelmon:charti_berry";
	public static final String KASIB_BERRY = "pixelmon:kasib_berry";
	public static final String HABAN_BERRY = "pixelmon:haban_berry";
	public static final String COLBUR_BERRY = "pixelmon:colbur_berry";
	public static final String BABIRI_BERRY = "pixelmon:babiri_berry";
	public static final String CHILAN_BERRY = "pixelmon:chilan_berry";
	public static final String ROSELI_BERRY = "pixelmon:roseli_berry";
	public static final String GINEMA_BERRY = "pixelmon:ginema_berry";
	public static final String KEE_BERRY = "pixelmon:kee_berry";
	public static final String MARANGA_BERRY = "pixelmon:maranga_berry";
	public static final String SUN_STONE = "pixelmon:sun_stone";
	public static final String FIRE_STONE = "pixelmon:fire_stone";
	public static final String WATER_STONE = "pixelmon:water_stone";
	public static final String MOON_STONE = "pixelmon:moon_stone";
	public static final String THUNDER_STONE = "pixelmon:thunder_stone";
	public static final String LEAF_STONE = "pixelmon:leaf_stone";
	public static final String DAWN_STONE = "pixelmon:dawn_stone";
	public static final String DUSK_STONE = "pixelmon:dusk_stone";
	public static final String SHINY_STONE = "pixelmon:shiny_stone";
	public static final String ICE_STONE = "pixelmon:ice_stone";
	public static final String DUBIOUS_DISC = "pixelmon:dubious_disc";
	public static final String ELECTIRIZER = "pixelmon:electirizer";
	public static final String MAGMARIZER = "pixelmon:magmarizer";
	public static final String KINGS_ROCK = "pixelmon:kings_rock";
	public static final String PROTECTOR = "pixelmon:protector";
	public static final String UP_GRADE="pixelmon:up-grade";
	public static final String RAZOR_FANG = "pixelmon:razor_fang";
	public static final String DRAGON_SCALE = "pixelmon:dragon_scale";
	public static final String RAZOR_CLAW = "pixelmon:razor_claw";
	public static final String DEEP_SEA_TOOTH = "pixelmon:deep_sea_tooth";
	public static final String DEEP_SEA_SCALE = "pixelmon:deep_sea_scale";
	public static final String OVAL_STONE = "pixelmon:oval_stone";
	public static final String REAPER_CLOTH = "pixelmon:reaper_cloth";
	public static final String LIGHT_BALL = "pixelmon:light_ball";
	public static final String THICK_CLUB = "pixelmon:thick_club";
	public static final String POWER_HERB = "pixelmon:power_herb";
	public static final String MENTAL_HERB = "pixelmon:mental_herb";
	public static final String WHITE_HERB = "pixelmon:white_herb";
	public static final String BUG_GEM = "pixelmon:bug_gem";
	public static final String DARK_GEM = "pixelmon:dark_gem";
	public static final String DRAGON_GEM = "pixelmon:dragon_gem";
	public static final String ELECTRIC_GEM = "pixelmon:electric_gem";
	public static final String FAIRY_GEM = "pixelmon:fairy_gem";
	public static final String FIGHTING_GEM = "pixelmon:fighting_gem";
	public static final String FIRE_GEM = "pixelmon:fire_gem";
	public static final String FLYING_GEM = "pixelmon:flying_gem";
	public static final String GHOST_GEM = "pixelmon:ghost_gem";
	public static final String GRASS_GEM = "pixelmon:grass_gem";
	public static final String GROUND_GEM = "pixelmon:ground_gem";
	public static final String ICE_GEM = "pixelmon:ice_gem";
	public static final String NORMAL_GEM = "pixelmon:normal_gem";
	public static final String POISON_GEM = "pixelmon:poison_gem";
	public static final String PSYCHIC_GEM = "pixelmon:psychic_gem";
	public static final String ROCK_GEM = "pixelmon:rock_gem";
	public static final String STEEL_GEM = "pixelmon:steel_gem";
	public static final String WATER_GEM = "pixelmon:water_gem";
	public static final String MACHO_BRACE = "pixelmon:macho_brace";
	public static final String SOOTHE_BELL = "pixelmon:soothe_bell";
	public static final String SMOKE_BALL = "pixelmon:smoke_ball";
	public static final String WIDE_LENS = "pixelmon:wide_lens";
	public static final String SHELL_BELL = "pixelmon:shell_bell";
	public static final String METRONOME = "pixelmon:metronome";
	public static final String FOCUS_BAND = "pixelmon:focus_band";
	public static final String TOXIC_ORB = "pixelmon:toxic_orb";
	public static final String FLAME_ORB = "pixelmon:flame_orb";
	public static final String BLACK_SLUDGE = "pixelmon:black_sludge";
	public static final String SCOPE_LENS = "pixelmon:scope_lens";
	public static final String AIR_BALLOON = "pixelmon:air_balloon";
	public static final String DAMP_ROCK = "pixelmon:damp_rock";
	public static final String HEAT_ROCK = "pixelmon:heat_rock";
	public static final String ICY_ROCK = "pixelmon:icy_rock";
	public static final String SMOOTH_ROCK = "pixelmon:smooth_rock";
	public static final String RED_CARD = "pixelmon:red_card";
	public static final String LIGHT_CLAY = "pixelmon:light_clay";
	public static final String QUICK_CLAW = "pixelmon:quick_claw";
	public static final String ZOOM_LENS = "pixelmon:zoom_lens";
	public static final String BRIGHT_POWDER = "pixelmon:bright_powder";
	public static final String LAGGING_TAIL = "pixelmon:lagging_tail";
	public static final String EJECT_BUTTON = "pixelmon:eject_button";
	public static final String IRON_BALL = "pixelmon:iron_ball";
	public static final String FULL_INCENSE = "pixelmon:full_incense";
	public static final String LAX_INCENSE = "pixelmon:lax_incense";
	public static final String LUCK_INCENSE = "pixelmon:luck_incense";
	public static final String ODD_INCENSE = "pixelmon:odd_incense";
	public static final String ROCK_INCENSE = "pixelmon:rock_incense";
	public static final String ROSE_INCENSE = "pixelmon:rose_incense";
	public static final String SEA_INCENSE = "pixelmon:sea_incense";
	public static final String WAVE_INCENSE = "pixelmon:wave_incense";
	public static final String BLACK_BELT = "pixelmon:black_belt";
	public static final String BLACK_GLASSES = "pixelmon:black_glasses";
	public static final String CHARCOAL = "pixelmon:charcoal";
	public static final String DRAGON_FANG = "pixelmon:dragon_fang";
	public static final String HARD_STONE = "pixelmon:hard_stone";
	public static final String MAGNET = "pixelmon:magnet";
	public static final String METAL_COAT = "pixelmon:metal_coat";
	public static final String MIRACLE_SEED = "pixelmon:miracle_seed";
	public static final String MYSTIC_WATER = "pixelmon:mystic_water";
	public static final String NEVER_MELT_ICE = "pixelmon:never_melt_ice";
	public static final String POISON_BARB = "pixelmon:poison_barb";
	public static final String PRISM_SCALE = "pixelmon:prism_scale";
	public static final String SHARP_BEAK = "pixelmon:sharp_beak";
	public static final String SILK_SCARF = "pixelmon:silk_scarf";
	public static final String SILVER_POWDER = "pixelmon:silver_powder";
	public static final String SOFT_SAND = "pixelmon:soft_sand";
	public static final String SPELL_TAG = "pixelmon:spell_tag";
	public static final String TWISTED_SPOON = "pixelmon:twisted_spoon";
	public static final String PIXIE_PLATE = "pixelmon:pixie_plate";
	public static final String AMULET_COIN = "pixelmon:amulet_coin";
	public static final String SAFETY_GOGGLES = "pixelmon:safety_goggles";
	public static final String TM1 = "pixelmon:tm1";
	public static final String TM9 = "pixelmon:tm9";
	public static final String TM20 = "pixelmon:tm20";
	public static final String TM21 = "pixelmon:tm21";
	public static final String TM23 = "pixelmon:tm23";
	public static final String TM28 = "pixelmon:tm28";
	public static final String TM32 = "pixelmon:tm32";
	public static final String TM39 = "pixelmon:tm39";
	public static final String TM40 = "pixelmon:tm40";
	public static final String TM41 = "pixelmon:tm41";
	public static final String TM46 = "pixelmon:tm46";
	public static final String TM47 = "pixelmon:tm47";
	public static final String TM56 = "pixelmon:tm56";
	public static final String TM57 = "pixelmon:tm57";
	public static final String TM58 = "pixelmon:tm58";
	public static final String TM67 = "pixelmon:tm67";
	public static final String TM77 = "pixelmon:tm77";
	public static final String TM78 = "pixelmon:tm78";
	public static final String TM79 = "pixelmon:tm79";
	public static final String TM83 = "pixelmon:tm83";
	public static final String TM85 = "pixelmon:tm85";
	public static final String TM88 = "pixelmon:tm88";
	public static final String TM94 = "pixelmon:tm94";
	public static final String TM95 = "pixelmon:tm95";
	public static final String TM96 = "pixelmon:tm96";
	public static final String TM97 = "pixelmon:tm97";
	public static final String TM102 = "pixelmon:tm102";
	public static final String TM104 = "pixelmon:tm104";
	public static final String TM106 = "pixelmon:tm106";
	public static final String TM107 = "pixelmon:tm107";
	public static final String TM109 = "pixelmon:tm109";
	public static final String TM114 = "pixelmon:tm114";
	public static final String TM115 = "pixelmon:tm115";
	public static final String TM116 = "pixelmon:tm116";
	public static final String TM117 = "pixelmon:tm117";
	public static final String TM118 = "pixelmon:tm118";
	public static final String TM119 = "pixelmon:tm119";
	public static final String TM121 = "pixelmon:tm121";
	public static final String TM122 = "pixelmon:tm122";
	public static final String TM125 = "pixelmon:tm125";
	public static final String TM127 = "pixelmon:tm127";
	public static final String TM129 = "pixelmon:tm129";
	public static final String TM135 = "pixelmon:tm135";
	public static final String TM137 = "pixelmon:tm137";
	public static final String TM144 = "pixelmon:tm144";
	public static final String TM147 = "pixelmon:tm147";
	public static final String TM149 = "pixelmon:tm149";
	public static final String TM151 = "pixelmon:tm151";
	public static final String TM152 = "pixelmon:tm152";
	public static final String TM153 = "pixelmon:tm153";
	public static final String TM154 = "pixelmon:tm154";
	public static final String TM156 = "pixelmon:tm156";
	public static final String TM159 = "pixelmon:tm159";
	public static final String TM165 = "pixelmon:tm165";
	public static final String TM167 = "pixelmon:tm167";
	public static final String TM168 = "pixelmon:tm168";
	public static final String TM171 = "pixelmon:tm171";
	public static final String TM172 = "pixelmon:tm172";
	public static final String TM173 = "pixelmon:tm173";
	public static final String TM174 = "pixelmon:tm174";
	public static final String HM1 = "pixelmon:hm1";
	public static final String HM4 = "pixelmon:hm4";
	public static final String HM6 = "pixelmon:hm6";
	public static final String HM8 = "pixelmon:hm8";
	public static final String HM9 = "pixelmon:hm9";
	public static final String HM10 = "pixelmon:hm10";
	public static final String ORB = "pixelmon:orb";
	public static final String RANCH_UPGRADE = "pixelmon:ranch_upgrade";
	public static final String HOURGLASS_GOLD = "pixelmon:hourglass_gold";
	public static final String EXP_SHARE = "pixelmon:exp_share";
	public static final String HEAVY_DUTY_BOOTS = "pixelmon:heavy_duty_boots";
	public static final String THROAT_SPRAY = "pixelmon:throat_spray";
	public static final String ROOM_SERVICE = "pixelmon:room_service";

	public static List<String> drops = new ArrayList<String>();

	public static void init() {
		drops.add(PP_UP);
		drops.add(CHERISH_BALL);
		drops.add(LUM_BERRY);
		drops.add(SITRUS_BERRY);
		drops.add(LIECHI_BERRY);
		drops.add(SALAC_BERRY);
		drops.add(PETAYA_BERRY);
		drops.add(CUSTAP_BERRY);
		drops.add(OCCA_BERRY);
		drops.add(PASSHO_BERRY);
		drops.add(WACAN_BERRY);
		drops.add(RINDO_BERRY);
		drops.add(YACHE_BERRY);
		drops.add(CHOPLE_BERRY);
		drops.add(KEBIA_BERRY);
		drops.add(SHUCA_BERRY);
		drops.add(COBA_BERRY);
		drops.add(PAYAPA_BERRY);
		drops.add(TANGA_BERRY);
		drops.add(CHARTI_BERRY);
		drops.add(KASIB_BERRY);
		drops.add(HABAN_BERRY);
		drops.add(COLBUR_BERRY);
		drops.add(BABIRI_BERRY);
		drops.add(CHILAN_BERRY);
		drops.add(ROSELI_BERRY);
		drops.add(GINEMA_BERRY);
		drops.add(KEE_BERRY);
		drops.add(MARANGA_BERRY);
		drops.add(SUN_STONE);
		drops.add(FIRE_STONE);
		drops.add(WATER_STONE);
		drops.add(MOON_STONE);
		drops.add(THUNDER_STONE);
		drops.add(LEAF_STONE);
		drops.add(DAWN_STONE);
		drops.add(DUSK_STONE);
		drops.add(SHINY_STONE);
		drops.add(ICE_STONE);
		drops.add(DUBIOUS_DISC);
		drops.add(ELECTIRIZER);
		drops.add(MAGMARIZER);
		drops.add(KINGS_ROCK);
		drops.add(PROTECTOR);
		drops.add(UP_GRADE);
		drops.add(RAZOR_FANG);
		drops.add(DRAGON_SCALE);
		drops.add(RAZOR_CLAW);
		drops.add(DEEP_SEA_TOOTH);
		drops.add(DEEP_SEA_SCALE);
		drops.add(OVAL_STONE);
		drops.add(REAPER_CLOTH);
		drops.add(LIGHT_BALL);
		drops.add(THICK_CLUB);
		drops.add(POWER_HERB);
		drops.add(MENTAL_HERB);
		drops.add(WHITE_HERB);
		drops.add(BUG_GEM);
		drops.add(DARK_GEM);
		drops.add(DRAGON_GEM);
		drops.add(ELECTRIC_GEM);
		drops.add(FAIRY_GEM);
		drops.add(FIGHTING_GEM);
		drops.add(FIRE_GEM);
		drops.add(FLYING_GEM);
		drops.add(GHOST_GEM);
		drops.add(GRASS_GEM);
		drops.add(GROUND_GEM);
		drops.add(ICE_GEM);
		drops.add(NORMAL_GEM);
		drops.add(POISON_GEM);
		drops.add(PSYCHIC_GEM);
		drops.add(ROCK_GEM);
		drops.add(STEEL_GEM);
		drops.add(WATER_GEM);
		drops.add(MACHO_BRACE);
		drops.add(SOOTHE_BELL);
		drops.add(SMOKE_BALL);
		drops.add(WIDE_LENS);
		drops.add(SHELL_BELL);
		drops.add(METRONOME);
		drops.add(FOCUS_BAND);
		drops.add(TOXIC_ORB);
		drops.add(FLAME_ORB);
		drops.add(BLACK_SLUDGE);
		drops.add(SCOPE_LENS);
		drops.add(AIR_BALLOON);
		drops.add(DAMP_ROCK);
		drops.add(HEAT_ROCK);
		drops.add(ICY_ROCK);
		drops.add(SMOOTH_ROCK);
		drops.add(RED_CARD);
		drops.add(LIGHT_CLAY);
		drops.add(QUICK_CLAW);
		drops.add(ZOOM_LENS);
		drops.add(BRIGHT_POWDER);
		drops.add(LAGGING_TAIL);
		drops.add(EJECT_BUTTON);
		drops.add(IRON_BALL);
		drops.add(FULL_INCENSE);
		drops.add(LAX_INCENSE);
		drops.add(LUCK_INCENSE);
		drops.add(ODD_INCENSE);
		drops.add(ROCK_INCENSE);
		drops.add(ROSE_INCENSE);
		drops.add(SEA_INCENSE);
		drops.add(WAVE_INCENSE);
		drops.add(BLACK_BELT);
		drops.add(BLACK_GLASSES);
		drops.add(CHARCOAL);
		drops.add(DRAGON_FANG);
		drops.add(HARD_STONE);
		drops.add(MAGNET);
		drops.add(METAL_COAT);
		drops.add(MIRACLE_SEED);
		drops.add(MYSTIC_WATER);
		drops.add(NEVER_MELT_ICE);
		drops.add(POISON_BARB);
		drops.add(PRISM_SCALE);
		drops.add(SHARP_BEAK);
		drops.add(SILK_SCARF);
		drops.add(SILVER_POWDER);
		drops.add(SOFT_SAND);
		drops.add(SPELL_TAG);
		drops.add(TWISTED_SPOON);
		drops.add(PIXIE_PLATE);
		drops.add(AMULET_COIN);
		drops.add(SAFETY_GOGGLES);
		drops.add(TM1);
		drops.add(TM9);
		drops.add(TM20);
		drops.add(TM21);
		drops.add(TM23);
		drops.add(TM28);
		drops.add(TM32);
		drops.add(TM39);
		drops.add(TM40);
		drops.add(TM41);
		drops.add(TM46);
		drops.add(TM47);
		drops.add(TM56);
		drops.add(TM57);
		drops.add(TM58);
		drops.add(TM67);
		drops.add(TM77);
		drops.add(TM78);
		drops.add(TM79);
		drops.add(TM83);
		drops.add(TM85);
		drops.add(TM88);
		drops.add(TM94);
		drops.add(TM95);
		drops.add(TM96);
		drops.add(TM97);
		drops.add(TM102);
		drops.add(TM104);
		drops.add(TM106);
		drops.add(TM107);
		drops.add(TM109);
		drops.add(TM114);
		drops.add(TM115);
		drops.add(TM116);
		drops.add(TM117);
		drops.add(TM118);
		drops.add(TM119);
		drops.add(TM121);
		drops.add(TM122);
		drops.add(TM125);
		drops.add(TM127);
		drops.add(TM129);
		drops.add(TM135);
		drops.add(TM137);
		drops.add(TM144);
		drops.add(TM147);
		drops.add(TM149);
		drops.add(TM151);
		drops.add(TM152);
		drops.add(TM153);
		drops.add(TM154);
		drops.add(TM156);
		drops.add(TM159);
		drops.add(TM165);
		drops.add(TM167);
		drops.add(TM168);
		drops.add(TM171);
		drops.add(TM172);
		drops.add(TM173);
		drops.add(TM174);
		drops.add(HM1);
		drops.add(HM4);
		drops.add(HM6);
		drops.add(HM8);
		drops.add(HM9);
		drops.add(HM10);
		drops.add(ORB);
		drops.add(RANCH_UPGRADE);
		drops.add(HOURGLASS_GOLD);
		drops.add(EXP_SHARE);
		drops.add(HEAVY_DUTY_BOOTS);
		drops.add(THROAT_SPRAY);
		drops.add(ROOM_SERVICE);
	}
}
