package com.pippohsios.betterpixelmon.storage;

import java.util.ArrayList;
import java.util.List;

public class UltraSpaceDropStorage {
	public static final String BUGINIUM_Z = "pixelmon:buginium_z";
	public static final String DARKINIUM_Z = "pixelmon:darkinium_z";
	public static final String DRAGONIUM_Z = "pixelmon:dragonium_z";
	public static final String ELECTRIUM_Z = "pixelmon:electrium_z";
	public static final String FAIRIUM_Z = "pixelmon:fairium_z";
	public static final String FIGHTINIUM_Z = "pixelmon:fightinium_z";
	public static final String FIRIUM_Z = "pixelmon:firium_z";
	public static final String FLYINIUM_Z = "pixelmon:flyinium_z";
	public static final String GHOSTIUM_Z = "pixelmon:ghostium_z";
	public static final String GRASSIUM_Z = "pixelmon:grassium_z";
	public static final String GROUNDIUM_Z = "pixelmon:groundium_z";
	public static final String ICIUM_Z = "pixelmon:icium_z";
	public static final String NORMALIUM_Z = "pixelmon:normalium_z";
	public static final String POISONIUM_Z = "pixelmon:poisonium_z";
	public static final String PSYCHIUM_Z = "pixelmon:psychium_z";
	public static final String ROCKIUM_Z = "pixelmon:rockium_z";
	public static final String STEELIUM_Z = "pixelmon:steelium_z";
	public static final String WATERIUM_Z = "pixelmon:waterium_z";
	public static final String BEAST_BALL = "pixelmon:beast_ball";
	public static final String SAFETY_GOGGLES = "pixelmon:safety_goggles";
	public static final String MEADOW_PLATE = "pixelmon:meadow_plate";
	public static final String FLAME_PLATE = "pixelmon:flame_plate";
	public static final String SPLASH_PLATE = "pixelmon:splash_plate";
	public static final String SKY_PLATE = "pixelmon:sky_plate";
	public static final String INSECT_PLATE = "pixelmon:insect_plate";
	public static final String TOXIC_PLATE = "pixelmon:toxic_plate";
	public static final String ZAP_PLATE = "pixelmon:zap_plate";
	public static final String MIND_PLATE = "pixelmon:mind_plate";
	public static final String STONE_PLATE = "pixelmon:stone_plate";
	public static final String EARTH_PLATE = "pixelmon:earth_plate";
	public static final String DREAD_PLATE = "pixelmon:dread_plate";
	public static final String SPOOKY_PLATE = "pixelmon:spooky_plate";
	public static final String IRON_PLATE = "pixelmon:iron_plate";
	public static final String FIST_PLATE = "pixelmon:fist_plate";
	public static final String ICICLE_PLATE = "pixelmon:icicle_plate";
	public static final String DRACO_PLATE = "pixelmon:draco_plate";
	public static final String PIXIE_PLATE = "pixelmon:pixie_plate";
	public static final String GRASS_MEMORY = "pixelmon:grass_memory";
	public static final String FIRE_MEMORY = "pixelmon:fire_memory";
	public static final String WATER_MEMORY = "pixelmon:water_memory";
	public static final String FLYING_MEMORY = "pixelmon:flying_memory";
	public static final String BUG_MEMORY = "pixelmon:bug_memory";
	public static final String POISON_MEMORY = "pixelmon:poison_memory";
	public static final String ELECTRIC_MEMORY = "pixelmon:electric_memory";
	public static final String PSYCHIC_MEMORY = "pixelmon:psychic_memory";
	public static final String ROCK_MEMORY = "pixelmon:rock_memory";
	public static final String GROUND_MEMORY = "pixelmon:ground_memory";
	public static final String DARK_MEMORY = "pixelmon:dark_memory";
	public static final String GHOST_MEMORY = "pixelmon:ghost_memory";
	public static final String STEEL_MEMORY = "pixelmon:steel_memory";
	public static final String FIGHTING_MEMORY = "pixelmon:fighting_memory";
	public static final String ICE_MEMORY = "pixelmon:ice_memory";
	public static final String DRAGON_MEMORY = "pixelmon:dragon_memory";
	public static final String FAIRY_MEMORY = "pixelmon:fairy_memory";

	public static List<String> drops = new ArrayList<String>();

	public static void init() {
		drops.add(BUGINIUM_Z);
		drops.add(DARKINIUM_Z);
		drops.add(DRAGONIUM_Z);
		drops.add(ELECTRIUM_Z);
		drops.add(FAIRIUM_Z);
		drops.add(FIGHTINIUM_Z);
		drops.add(FIRIUM_Z);
		drops.add(FLYINIUM_Z);
		drops.add(GHOSTIUM_Z);
		drops.add(GRASSIUM_Z);
		drops.add(GROUNDIUM_Z);
		drops.add(ICIUM_Z);
		drops.add(NORMALIUM_Z);
		drops.add(POISONIUM_Z);
		drops.add(PSYCHIUM_Z);
		drops.add(ROCKIUM_Z);
		drops.add(STEELIUM_Z);
		drops.add(WATERIUM_Z);
		drops.add(BEAST_BALL);
		drops.add(SAFETY_GOGGLES);
		drops.add(MEADOW_PLATE);
		drops.add(FLAME_PLATE);
		drops.add(SPLASH_PLATE);
		drops.add(SKY_PLATE);
		drops.add(INSECT_PLATE);
		drops.add(TOXIC_PLATE);
		drops.add(ZAP_PLATE);
		drops.add(MIND_PLATE);
		drops.add(STONE_PLATE);
		drops.add(EARTH_PLATE);
		drops.add(DREAD_PLATE);
		drops.add(SPOOKY_PLATE);
		drops.add(IRON_PLATE);
		drops.add(FIST_PLATE);
		drops.add(ICICLE_PLATE);
		drops.add(DRACO_PLATE);
		drops.add(PIXIE_PLATE);
		drops.add(GRASS_MEMORY);
		drops.add(FIRE_MEMORY);
		drops.add(WATER_MEMORY);
		drops.add(FLYING_MEMORY);
		drops.add(BUG_MEMORY);
		drops.add(POISON_MEMORY);
		drops.add(ELECTRIC_MEMORY);
		drops.add(PSYCHIC_MEMORY);
		drops.add(ROCK_MEMORY);
		drops.add(GROUND_MEMORY);
		drops.add(DARK_MEMORY);
		drops.add(GHOST_MEMORY);
		drops.add(STEEL_MEMORY);
		drops.add(FIGHTING_MEMORY);
		drops.add(ICE_MEMORY);
		drops.add(DRAGON_MEMORY);
		drops.add(FAIRY_MEMORY);
	}
}
